/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.pesquisas;

import java.awt.Frame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Utilitarios;
import persistence.DAO;
import telas.cadastros.Fornecedor;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class PesqFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form PesqFornecedor
     */
    
    //  Variavel para usar as consultas na pesquisa
    private String where;
    
     //  Variavel para usar as consultas na pesquisa
    List<models.Fornecedor> lista;
    
    private Frame parent;
    
    public PesqFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        
        jTable_Fornecedor_.setCellSelectionEnabled(false);
        
        //  Inicialização da variavel que será usada nas pesquisas
        where = "";
      
    }// Fim do construtor PesqFornecedor
    
    //  Método que popula a tabela
    private void atualiza()
    {
        
        String[] titulos = new String[]{"Número", "Nome", "CPF/CNPJ", "Email"};
        
        lista = DAO.consultaSQL(models.Fornecedor.class, where);
        
        Object[][] dados = new Object[lista.size()][titulos.length];
        
        for(int i = 0; i < lista.size(); i++)
        {
            
            dados[i][0] = lista.get(i).getId();
            dados[i][1] = lista.get(i).getNome();
            dados[i][2] = lista.get(i).getCpfCnpj();
            dados[i][3] = lista.get(i).getEmail();
            
        }// Fim do método de repetição for
        
        DefaultTableModel dtm = new DefaultTableModel(dados, titulos);
        
        jTable_Fornecedor_.setModel(dtm);
        
    }// Fim do método atualiza

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Limpar = new javax.swing.JButton();
        jButton_Imprimir = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Incluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Empresas = new javax.swing.JLabel();
        jTextField_Pesquisa = new javax.swing.JTextField();
        jButton_Pesquisar_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Fornecedor_ = new javax.swing.JTable();
        jLabel_DataAbertura2 = new javax.swing.JLabel();
        jButton_Limpar1 = new javax.swing.JButton();
        jButton_Imprimir1 = new javax.swing.JButton();
        jButton_Editar1 = new javax.swing.JButton();
        jButton_Incluir1 = new javax.swing.JButton();

        jButton_Limpar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Limpar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Limpar.setText("LIMPAR");
        jButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimparActionPerformed(evt);
            }
        });

        jButton_Imprimir.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Imprimir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Imprimir.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Imprimir.setText("IMPRIMIR");
        jButton_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirActionPerformed(evt);
            }
        });

        jButton_Editar.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Editar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Editar.setText("EDITAR");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Incluir.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Incluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Incluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Incluir.setText("INCLUIR");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Empresas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Empresas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Empresas.setText("FORNECEDORES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Empresas)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Empresas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PesquisaActionPerformed(evt);
            }
        });
        jTextField_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PesquisaKeyPressed(evt);
            }
        });

        jButton_Pesquisar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Pesquisar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Pesquisar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Pesquisar_.setText("PESQUISAR");
        jButton_Pesquisar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pesquisar_ActionPerformed(evt);
            }
        });

        jTable_Fornecedor_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Nome", "CPF/CNPJ", "Email"
            }
        ));
        jTable_Fornecedor_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Fornecedor_MouseClicked(evt);
            }
        });
        jTable_Fornecedor_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_Fornecedor_KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Fornecedor_);

        jLabel_DataAbertura2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DataAbertura2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DataAbertura2.setText("Nome ou Id");

        jButton_Limpar1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Limpar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Limpar1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Limpar1.setText("LIMPAR");
        jButton_Limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Limpar1ActionPerformed(evt);
            }
        });

        jButton_Imprimir1.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Imprimir1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Imprimir1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Imprimir1.setText("IMPRIMIR");
        jButton_Imprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Imprimir1ActionPerformed(evt);
            }
        });

        jButton_Editar1.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Editar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Editar1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Editar1.setText("EDITAR");
        jButton_Editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Editar1ActionPerformed(evt);
            }
        });

        jButton_Incluir1.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Incluir1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Incluir1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Incluir1.setText("INCLUIR");
        jButton_Incluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Incluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Incluir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Imprimir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Limpar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_DataAbertura2)
                                    .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Pesquisar_)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Pesquisar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DataAbertura2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Limpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Imprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PesquisaActionPerformed

    private void jTextField_PesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PesquisaKeyPressed

    }//GEN-LAST:event_jTextField_PesquisaKeyPressed

    private void jButton_Pesquisar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pesquisar_ActionPerformed
        //  Pesquisa por nome
        where = " and o.nome like '%" + jTextField_Pesquisa.getText() + "%'";
        
        //  Pesquis por id
        if(Utilitarios.isNumeric(jTextField_Pesquisa.getText()))
        {
            where += " or o.id='" + jTextField_Pesquisa.getText() + "'";
        }// Fim do bloco de condição if
        
        //  Chamando o método que popula a tabela
        atualiza();
    }//GEN-LAST:event_jButton_Pesquisar_ActionPerformed

    private void jTable_Fornecedor_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_Fornecedor_KeyPressed
       
        // Chamando a tela de fornecedor e exibindo registro        
        new Fornecedor(parent, true, lista.get(jTable_Fornecedor_.getSelectedRow())).setVisible(true);
        
        //  Atualizando tabela
        atualiza();
    }//GEN-LAST:event_jTable_Fornecedor_KeyPressed

    private void jTable_Fornecedor_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Fornecedor_MouseClicked
       
    }//GEN-LAST:event_jTable_Fornecedor_MouseClicked

    private void jButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimparActionPerformed

        DefaultTableModel table = (DefaultTableModel)jTable_Fornecedor_.getModel();
        table.setRowCount(0);

    }//GEN-LAST:event_jButton_LimparActionPerformed

    private void jButton_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirActionPerformed
        try
        {
            if (! jTable_Fornecedor_.print())
            {
                System.err.println("Usuario cancelou a impressao");
            }// Fim do bloco if
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Nao impressa %s%n", e.getMessage());
        }// Fim do bloco try-catch
    }//GEN-LAST:event_jButton_ImprimirActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed

        //  Chamando a tela de chamado e exibindo registro
        new Fornecedor(parent, true, lista.get(jTable_Fornecedor_.getSelectedRow())).setVisible(true);

        //  Atualizando tabela
        atualiza();
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed

        new Fornecedor(parent, true).setVisible(true);
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    private void jButton_Limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Limpar1ActionPerformed

        DefaultTableModel table = (DefaultTableModel)jTable_Fornecedor_.getModel();
        table.setRowCount(0);

    }//GEN-LAST:event_jButton_Limpar1ActionPerformed

    private void jButton_Imprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Imprimir1ActionPerformed
        try
        {
            if (! jTable_Fornecedor_.print())
            {
                System.err.println("Usuario cancelou a impressao");
            }// Fim do bloco if
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Nao impressa %s%n", e.getMessage());
        }// Fim do bloco try-catch
    }//GEN-LAST:event_jButton_Imprimir1ActionPerformed

    private void jButton_Editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Editar1ActionPerformed

        //  Chamando a tela e exibindo registro
        new Fornecedor(parent, true, lista.get(jTable_Fornecedor_.getSelectedRow())).setVisible(true);

        //  Atualizando tabela
        atualiza();
    }//GEN-LAST:event_jButton_Editar1ActionPerformed

    private void jButton_Incluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Incluir1ActionPerformed

        //  Chamado a tela para incluir novo registro
        new Fornecedor(parent, true).setVisible(true);
        
        //  Atualizando tabela
        atualiza();
    }//GEN-LAST:event_jButton_Incluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesqFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesqFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesqFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesqFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesqFornecedor dialog = new PesqFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Editar1;
    private javax.swing.JButton jButton_Imprimir;
    private javax.swing.JButton jButton_Imprimir1;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JButton jButton_Incluir1;
    private javax.swing.JButton jButton_Limpar;
    private javax.swing.JButton jButton_Limpar1;
    private javax.swing.JButton jButton_Pesquisar_;
    private javax.swing.JLabel jLabel_DataAbertura2;
    private javax.swing.JLabel jLabel_Empresas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Fornecedor_;
    private javax.swing.JTextField jTextField_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
