/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.pesquisas;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import models.Utilitarios;
import persistence.DAO;
import telas.cadastros.Compra;
import telas.cadastros.Produto;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class PesqCompra extends javax.swing.JDialog {

    /**
     * Creates new form PesqCompra
     */
    
    //  Lista de compras
    List <models.Compra> lista;
    
    //  Variavel para usar as consultas na pesquisa
    private String where;
    
    private Frame parent;
    
    public PesqCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jTable_Compra_.setCellSelectionEnabled(false);
        
        this.parent = parent;
        
        //  Inicialização da variavel que será usada nas pesquisas
        where = "";
        
        atualizaComboBox();
               
    }// Fim do construtor
    
    //  Método que popula a tabela
    private void atualiza()
    {
        
        String[] titulos = new String[]{"ID", "Produto", "Fornecedor", "Data Compra", "Valor"};
        
        lista = DAO.consultaSQL(models.Compra.class, where);
        
        Object[][] dados = new Object[lista.size()][titulos.length];
        
        for(int i = 0; i < lista.size(); i++)
        {
            
            dados[i][0] = lista.get(i).getId();
            dados[i][1] = lista.get(i).getIdProduto();
            dados[i][2] = lista.get(i).getIdFornecedor();
            dados[i][3] = lista.get(i).dataCompra();
            dados[i][4] = lista.get(i).getValor();
            
        }// Fim do bloco de repetição for
        
        DefaultTableModel dtm = new DefaultTableModel(dados, titulos);
        
        jTable_Compra_.setModel(dtm);     
        
        
    }// Fim do método atualiza
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        List fornecedor = new LinkedList();
        fornecedor.add("Selecione");
        fornecedor.addAll(DAO.consulta(models.Fornecedor.class, ""));
        jComboBox_Fornecedor_.setModel(new DefaultComboBoxModel<>(fornecedor.toArray()));
        
        List produto = new LinkedList();
        produto.add("Selecione");
        produto.addAll(DAO.consulta(models.Produto.class, ""));
        jComboBox_Produto_.setModel(new DefaultComboBoxModel<>(produto.toArray()));
        
    }// Fim do método atualizaComboBox

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Clientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Compra_ = new javax.swing.JTable();
        jLabel_DataAbertura2 = new javax.swing.JLabel();
        jButton_Pesquisar_ = new javax.swing.JButton();
        jLabel_DataCompra = new javax.swing.JLabel();
        jDateChooser_DataCompra = new com.toedter.calendar.JDateChooser();
        jLabel_Produto = new javax.swing.JLabel();
        jComboBox_Produto_ = new javax.swing.JComboBox<>();
        jComboBox_Fornecedor_ = new javax.swing.JComboBox<>();
        jLabel_Produto1 = new javax.swing.JLabel();
        jTextField_id_ = new javax.swing.JTextField();
        jButton_Limpar = new javax.swing.JButton();
        jButton_Imprimir = new javax.swing.JButton();
        jButton_Editar = new javax.swing.JButton();
        jButton_Incluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Clientes.setText("COMPRAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Clientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Clientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_Compra_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Fornecedor", "Data Compra", "Valor"
            }
        ));
        jTable_Compra_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Compra_MouseClicked(evt);
            }
        });
        jTable_Compra_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_Compra_KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Compra_);

        jLabel_DataAbertura2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DataAbertura2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DataAbertura2.setText("Id");

        jButton_Pesquisar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Pesquisar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Pesquisar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Pesquisar_.setText("PESQUISAR");
        jButton_Pesquisar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pesquisar_ActionPerformed(evt);
            }
        });

        jLabel_DataCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DataCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DataCompra.setText("Data Compra");

        jDateChooser_DataCompra.setDateFormatString("d '/' M '/' y");

        jLabel_Produto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Produto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Produto.setText("Produto");

        jComboBox_Produto_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Produto_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Produto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Produto_ActionPerformed(evt);
            }
        });

        jComboBox_Fornecedor_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Fornecedor_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Fornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Fornecedor_ActionPerformed(evt);
            }
        });

        jLabel_Produto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Produto1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Produto1.setText("Fornecedor");

        jButton_Limpar.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Limpar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Limpar.setText("LIMPAR");
        jButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimparActionPerformed(evt);
            }
        });

        jButton_Imprimir.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Imprimir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Imprimir.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Imprimir.setText("IMPRIMIR");
        jButton_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirActionPerformed(evt);
            }
        });

        jButton_Editar.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Editar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Editar.setText("EDITAR");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Incluir.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Incluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Incluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Incluir.setText("INCLUIR");
        jButton_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Incluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Imprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Limpar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jTextField_id_, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_DataAbertura2)
                                    .addGap(71, 71, 71)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_DataCompra)
                                .addComponent(jDateChooser_DataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Produto)
                                .addComponent(jComboBox_Produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_Produto1)
                                .addComponent(jComboBox_Fornecedor_, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Pesquisar_)
                            .addGap(28, 28, 28))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_Produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_DataAbertura2)
                            .addComponent(jLabel_DataCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser_DataCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jTextField_id_)))
                    .addComponent(jButton_Pesquisar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Produto)
                        .addGap(37, 37, 37))
                    .addComponent(jComboBox_Fornecedor_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Produto1)
                        .addGap(32, 32, 32)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_Compra_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Compra_MouseClicked


    }//GEN-LAST:event_jTable_Compra_MouseClicked

    private void jTable_Compra_KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_Compra_KeyPressed
        
        //  Chamando a tela e exibindo registro
        new Compra(parent, true, lista.get(jTable_Compra_.getSelectedRow())).setVisible(true);
        
        //  Atualizando tabela
        atualiza();

    }//GEN-LAST:event_jTable_Compra_KeyPressed

    private void jButton_Pesquisar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pesquisar_ActionPerformed

        where = "";
        
        //  Pesquis por id
        if(Utilitarios.isNumeric(jTextField_id_.getText()))
        {
            where += " and o.id='" + jTextField_id_.getText() + "'";
        }// Fim do bloco de condição if
        
        //  Pesquisa por data de abertura
        if(jDateChooser_DataCompra.getDate() != null)
        {
            where += " and o.data_compra='" + new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser_DataCompra.getDate()) + "'";
        }// Fim do bloco de condição if
        
        //  Pesquisa por Produto
        if(jComboBox_Produto_.getSelectedIndex() > 0)
        {
            where += " and o.id_produto='" + ((models.Produto) jComboBox_Produto_.getSelectedItem()).getId()+ "'";
        }// Fim do bloco de condição if
        
        //  Pesquisa por Fornecedor
        if(jComboBox_Fornecedor_.getSelectedIndex() > 0)
        {
            where += " and o.id_fornecedor='" + ((models.Fornecedor) jComboBox_Fornecedor_.getSelectedItem()).getId()+ "'";
        }// Fim do bloco de condição if

        //  Chamando o método que popula a tabela
        atualiza();

    }//GEN-LAST:event_jButton_Pesquisar_ActionPerformed

    private void jComboBox_Produto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Produto_ActionPerformed

    }//GEN-LAST:event_jComboBox_Produto_ActionPerformed

    private void jComboBox_Fornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Fornecedor_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Fornecedor_ActionPerformed

    private void jButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimparActionPerformed

        DefaultTableModel table = (DefaultTableModel)jTable_Compra_.getModel();
        table.setRowCount(0);
    }//GEN-LAST:event_jButton_LimparActionPerformed

    private void jButton_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirActionPerformed
        try
        {
            if (! jTable_Compra_.print())
            {
                System.err.println("Usuario cancelou a impressao");
            }// Fim do bloc if
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Nao impressa %s%n", e.getMessage());
        }// Fim do bloco try-catch
    }//GEN-LAST:event_jButton_ImprimirActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed

        //  Chamando a tela e exibindo registro
        new Compra(parent, true, lista.get(jTable_Compra_.getSelectedRow())).setVisible(true);

        //  Atualizando tabela
        atualiza();
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IncluirActionPerformed
        
        //  Chamado a tela para incluir novo registro
        new Compra(parent, true).setVisible(true);
        
        //  Atualizando tabela
        atualiza();
        
    }//GEN-LAST:event_jButton_IncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesqCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesqCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesqCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesqCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesqCompra dialog = new PesqCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Imprimir;
    private javax.swing.JButton jButton_Incluir;
    private javax.swing.JButton jButton_Limpar;
    private javax.swing.JButton jButton_Pesquisar_;
    private javax.swing.JComboBox<Object> jComboBox_Fornecedor_;
    private javax.swing.JComboBox<Object> jComboBox_Produto_;
    private com.toedter.calendar.JDateChooser jDateChooser_DataCompra;
    private javax.swing.JLabel jLabel_Clientes;
    private javax.swing.JLabel jLabel_DataAbertura2;
    private javax.swing.JLabel jLabel_DataCompra;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_Produto1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Compra_;
    private javax.swing.JTextField jTextField_id_;
    // End of variables declaration//GEN-END:variables
}
