/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.List;
import javax.swing.JOptionPane;
import models.Tecnico;
import models.Utilitarios;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        Utilitarios.InserirIcone(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel_logo6 = new javax.swing.JLabel();
        jLabel_login6 = new javax.swing.JLabel();
        jTextField_Login = new javax.swing.JTextField();
        jLabel_Senha6 = new javax.swing.JLabel();
        jPasswordField_Senha = new javax.swing.JPasswordField();
        jButton_Entrar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Star - Gerenciador de Chamados v1.0.0");
        setUndecorated(true);
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_logo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-star-horizontal1.png"))); // NOI18N

        jLabel_login6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_login6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_login6.setText("Login:");

        jTextField_Login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LoginActionPerformed(evt);
            }
        });

        jLabel_Senha6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Senha6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Senha6.setText("Senha:");

        jPasswordField_Senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_Entrar.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Entrar.setText("Entrar");
        jButton_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntrarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_logo6, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_Login)
                                .addComponent(jLabel_login6)
                                .addComponent(jLabel_Senha6)
                                .addComponent(jPasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButton_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel_logo6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel_login6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel_Senha6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(685, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LoginActionPerformed

    }//GEN-LAST:event_jTextField_LoginActionPerformed

    private void jButton_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntrarActionPerformed
        String email = jTextField_Login.getText();
        String senha = this.jPasswordField_Senha.getText();

        models.Tecnico tecnico = new models.Tecnico();

        tecnico.setEmail(email);
        tecnico.setSenha(senha);

        List <models.Tecnico> lista = DAO.consultaSQL(models.Tecnico.class, "and o.email= '" + email + "' and o.senha='" + senha + "'");

        if(lista.size() > 0)
        {
            new Principal().setVisible(true);
            this.dispose();
        } else
        {
            JOptionPane.showMessageDialog(rootPane, "ERRO! LOGIN OU SENHA INCORRETO");
        }

    }//GEN-LAST:event_jButton_EntrarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Cancelar_;
    private javax.swing.JButton jButton_Cancelar_1;
    private javax.swing.JButton jButton_Cancelar_2;
    private javax.swing.JButton jButton_Cancelar_3;
    private javax.swing.JButton jButton_Cancelar_4;
    private javax.swing.JButton jButton_Cancelar_5;
    private javax.swing.JButton jButton_Entrar;
    private javax.swing.JButton jButton_Entrar_;
    private javax.swing.JButton jButton_Entrar_1;
    private javax.swing.JButton jButton_Entrar_2;
    private javax.swing.JButton jButton_Entrar_3;
    private javax.swing.JButton jButton_Entrar_4;
    private javax.swing.JButton jButton_Entrar_5;
    private javax.swing.JLabel jLabel_Senha;
    private javax.swing.JLabel jLabel_Senha1;
    private javax.swing.JLabel jLabel_Senha2;
    private javax.swing.JLabel jLabel_Senha3;
    private javax.swing.JLabel jLabel_Senha4;
    private javax.swing.JLabel jLabel_Senha5;
    private javax.swing.JLabel jLabel_Senha6;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_login1;
    private javax.swing.JLabel jLabel_login2;
    private javax.swing.JLabel jLabel_login3;
    private javax.swing.JLabel jLabel_login4;
    private javax.swing.JLabel jLabel_login5;
    private javax.swing.JLabel jLabel_login6;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_logo1;
    private javax.swing.JLabel jLabel_logo2;
    private javax.swing.JLabel jLabel_logo3;
    private javax.swing.JLabel jLabel_logo4;
    private javax.swing.JLabel jLabel_logo5;
    private javax.swing.JLabel jLabel_logo6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField_Senha;
    private javax.swing.JPasswordField jPasswordField_Senha_;
    private javax.swing.JPasswordField jPasswordField_Senha_1;
    private javax.swing.JPasswordField jPasswordField_Senha_2;
    private javax.swing.JPasswordField jPasswordField_Senha_3;
    private javax.swing.JPasswordField jPasswordField_Senha_4;
    private javax.swing.JPasswordField jPasswordField_Senha_5;
    private javax.swing.JTextField jTextField_Login;
    private javax.swing.JTextField jTextField_Login_;
    private javax.swing.JTextField jTextField_Login_1;
    private javax.swing.JTextField jTextField_Login_2;
    private javax.swing.JTextField jTextField_Login_3;
    private javax.swing.JTextField jTextField_Login_4;
    private javax.swing.JTextField jTextField_Login_5;
    // End of variables declaration//GEN-END:variables
}
