/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.cadastros.Tecnico;
import telas.cadastros.Situacao;
import telas.cadastros.BaixaProduto;
import telas.cadastros.Produto;
import telas.cadastros.Chamado;
import telas.cadastros.Cliente;
import telas.cadastros.Fornecedor;
import telas.cadastros.Empresa;
import telas.cadastros.Compra;
import telas.pesquisas.PesqTecnico;
import telas.pesquisas.PesqSituacao;
import telas.pesquisas.PesqProduto;
import telas.pesquisas.PesqFornecedor;
import telas.pesquisas.PesqEmpresa;
import telas.pesquisas.PesqCliente;
import telas.pesquisas.PesqChamado;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Utilitarios;
import persistence.DAO;
import telas.pesquisas.PesqCompra;


/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    List<models.Chamado> lista;
    
    private Frame parent;
    
    public Principal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        jLabelData.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
        
        Utilitarios.InserirIcone(this);
        
        //  Método que popula a tabela
        atualiza();
        
    }
    
    public void atualiza()
    {
        String[] titulos = new String[]{"Número", "Nome", "Data Abertura", "Cliente", "Prioridade", "Técnico Resp", "Vencimento"};
        
        lista = DAO.consultaSQL(models.Chamado.class, "and id_situacao = 1");    
        
        Object[][] dados = new Object[lista.size()][titulos.length];
        
        for(int i = 0; i < lista.size(); i++)
        {
            
            dados[i][0] = lista.get(i).getId();
            dados[i][1] = lista.get(i).getNome();
            dados[i][2] = lista.get(i).dataAbertura();
            dados[i][3] = lista.get(i).getIdCliente();
            dados[i][4] = lista.get(i).getIdPrioridade();
            dados[i][5] = lista.get(i).getIdTecnico();
            dados[i][6] = lista.get(i).dataVencimento();
            
        }// Fim do bloco de repetição for
        
        DefaultTableModel dtm = new DefaultTableModel(dados, titulos);
        
        jTable_Chamado.setModel(dtm);
        
    }// Fim do método atualiza

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel_Data = new javax.swing.JLabel();
        jPanel_Principal_ = new javax.swing.JPanel();
        jPanel_Chamados = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Chamado = new javax.swing.JTable();
        jLabel_ChamadoVencimento1 = new javax.swing.JLabel();
        jButton_Salvar_ = new javax.swing.JButton();
        jLabel_Logo = new javax.swing.JLabel();
        jPanel_Botoes_ = new javax.swing.JPanel();
        jButton_CriarChamado_ = new javax.swing.JButton();
        jLabel_CriarChamado = new javax.swing.JLabel();
        jButton_CadCompra_ = new javax.swing.JButton();
        jLabel_CadCompra = new javax.swing.JLabel();
        jLabel_CadCliente = new javax.swing.JLabel();
        jButton_CadCliente_ = new javax.swing.JButton();
        jButton_CadEmpresa = new javax.swing.JButton();
        jLabel_CadEmpresa = new javax.swing.JLabel();
        jButton_BaixaProduto_ = new javax.swing.JButton();
        jLabel_BaixaProduto = new javax.swing.JLabel();
        jLabel_Sair = new javax.swing.JLabel();
        jButton_Sair_ = new javax.swing.JButton();
        jMenuBar_Principal = new javax.swing.JMenuBar();
        jMenu_Chamados_ = new javax.swing.JMenu();
        jMenuItem_CadChamado_ = new javax.swing.JMenuItem();
        jMenuItem_PesqChamado_ = new javax.swing.JMenuItem();
        jMenu_Situacao_ = new javax.swing.JMenu();
        jMenuItem_CadSituacao_ = new javax.swing.JMenuItem();
        jMenuItem_PesqSituacao_ = new javax.swing.JMenuItem();
        jMenu_Clientes = new javax.swing.JMenu();
        jMenuItem_CadCliente_ = new javax.swing.JMenuItem();
        jMenuItem_PesqCliente = new javax.swing.JMenuItem();
        jMenu_Clientes1 = new javax.swing.JMenu();
        jMenuItem_CadEmpresa = new javax.swing.JMenuItem();
        jMenuItem_PesqEmpresa = new javax.swing.JMenuItem();
        jMenu_Fornecedores = new javax.swing.JMenu();
        jMenuItem_CadFornecedor_ = new javax.swing.JMenuItem();
        jMenuItem_PesqFornecedor_ = new javax.swing.JMenuItem();
        jMenu_Produtos = new javax.swing.JMenu();
        jMenuItem_CadProduto_ = new javax.swing.JMenuItem();
        jMenuItem_BaixaProduto_ = new javax.swing.JMenuItem();
        jMenuItem_PesqProduto_ = new javax.swing.JMenuItem();
        jMenu_Tecnico1 = new javax.swing.JMenu();
        jMenuItem_CadCompra_ = new javax.swing.JMenuItem();
        jMenuItem_PesqCompra_ = new javax.swing.JMenuItem();
        jMenu_Tecnico = new javax.swing.JMenu();
        jMenuItem_CadTecnico_ = new javax.swing.JMenuItem();
        jMenuItem_PesqTecnico_ = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel_Data.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_Data.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Data.setText("XX/XX/XX");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Star v1.1.3 - Gerenciador de Chamados");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel_Principal_.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Principal_.setForeground(new java.awt.Color(255, 255, 255));

        jPanel_Chamados.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Chamados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(134, 116, 178), 15));

        jLabelData.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setText("xx-xx-xxxx");

        jTable_Chamado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_Chamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Nome", "Data Abertura", "Cliente", "Prioridade", "Técnico Resp", "Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Chamado.setRowHeight(40);
        jTable_Chamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ChamadoMouseClicked(evt);
            }
        });
        jTable_Chamado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_ChamadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Chamado);

        jLabel_ChamadoVencimento1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_ChamadoVencimento1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_ChamadoVencimento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ChamadoVencimento1.setText("CHAMADOS EM ABERTO");

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("ATUALIZA");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ChamadosLayout = new javax.swing.GroupLayout(jPanel_Chamados);
        jPanel_Chamados.setLayout(jPanel_ChamadosLayout);
        jPanel_ChamadosLayout.setHorizontalGroup(
            jPanel_ChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChamadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Salvar_))
                    .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_ChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ChamadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_ChamadoVencimento1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_ChamadosLayout.setVerticalGroup(
            jPanel_ChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChamadosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_ChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ChamadosLayout.createSequentialGroup()
                    .addComponent(jLabel_ChamadoVencimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 441, Short.MAX_VALUE)))
        );

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-star3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_Principal_Layout = new javax.swing.GroupLayout(jPanel_Principal_);
        jPanel_Principal_.setLayout(jPanel_Principal_Layout);
        jPanel_Principal_Layout.setHorizontalGroup(
            jPanel_Principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Principal_Layout.createSequentialGroup()
                .addComponent(jPanel_Chamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Logo)
                .addContainerGap())
        );
        jPanel_Principal_Layout.setVerticalGroup(
            jPanel_Principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Principal_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Chamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_Principal_Layout.createSequentialGroup()
                .addComponent(jLabel_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        jPanel_Botoes_.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Botoes_.setForeground(new java.awt.Color(255, 255, 255));

        jButton_CriarChamado_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_CriarChamado_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desenvolvimento-de-software.png"))); // NOI18N
        jButton_CriarChamado_.setBorderPainted(false);
        jButton_CriarChamado_.setContentAreaFilled(false);
        jButton_CriarChamado_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CriarChamado_ActionPerformed(evt);
            }
        });

        jLabel_CriarChamado.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_CriarChamado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CriarChamado.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CriarChamado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CriarChamado.setText("Criar Chamado");

        jButton_CadCompra_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_CadCompra_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carrinho-de-compras.png"))); // NOI18N
        jButton_CadCompra_.setBorderPainted(false);
        jButton_CadCompra_.setContentAreaFilled(false);
        jButton_CadCompra_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadCompra_ActionPerformed(evt);
            }
        });

        jLabel_CadCompra.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_CadCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CadCompra.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CadCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CadCompra.setText("Cadastrar Compra");

        jLabel_CadCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CadCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CadCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CadCliente.setText("Cadastrar Cliente");

        jButton_CadCliente_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_CadCliente_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/avaliacao-do-cliente.png"))); // NOI18N
        jButton_CadCliente_.setBorderPainted(false);
        jButton_CadCliente_.setContentAreaFilled(false);
        jButton_CadCliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadCliente_ActionPerformed(evt);
            }
        });

        jButton_CadEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jButton_CadEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/empresa.png"))); // NOI18N
        jButton_CadEmpresa.setBorderPainted(false);
        jButton_CadEmpresa.setContentAreaFilled(false);
        jButton_CadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadEmpresaActionPerformed(evt);
            }
        });

        jLabel_CadEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CadEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CadEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CadEmpresa.setText("Cadastrar Empresa");

        jButton_BaixaProduto_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_BaixaProduto_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/produtos.png"))); // NOI18N
        jButton_BaixaProduto_.setBorder(null);
        jButton_BaixaProduto_.setBorderPainted(false);
        jButton_BaixaProduto_.setContentAreaFilled(false);
        jButton_BaixaProduto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BaixaProduto_ActionPerformed(evt);
            }
        });

        jLabel_BaixaProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_BaixaProduto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_BaixaProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_BaixaProduto.setText("Baixa Produto");

        jLabel_Sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Sair.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Sair.setText("Sair");

        jButton_Sair_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Sair_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        jButton_Sair_.setBorderPainted(false);
        jButton_Sair_.setContentAreaFilled(false);
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Botoes_Layout = new javax.swing.GroupLayout(jPanel_Botoes_);
        jPanel_Botoes_.setLayout(jPanel_Botoes_Layout);
        jPanel_Botoes_Layout.setHorizontalGroup(
            jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CriarChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jButton_CriarChamado_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_CadCompra_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CadCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton_CadCliente_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CadEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jButton_CadEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_BaixaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jButton_BaixaProduto_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Sair_, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(610, 610, 610))
        );
        jPanel_Botoes_Layout.setVerticalGroup(
            jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                                .addComponent(jButton_CriarChamado_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                                        .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_CadCompra_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_CadCliente_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Botoes_Layout.createSequentialGroup()
                                        .addComponent(jButton_CadEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_CadCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_CadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_CriarChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_CadEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                        .addComponent(jButton_BaixaProduto_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel_Botoes_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_BaixaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_Botoes_Layout.createSequentialGroup()
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addGap(20, 20, 20))
        );

        jMenuBar_Principal.setBackground(new java.awt.Color(72, 124, 189));
        jMenuBar_Principal.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar_Principal.setBorderPainted(false);

        jMenu_Chamados_.setBackground(new java.awt.Color(0, 51, 255));
        jMenu_Chamados_.setBorder(null);
        jMenu_Chamados_.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Chamados_.setText("Chamados");
        jMenu_Chamados_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadChamado_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadChamado_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadChamado_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadChamado_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jMenuItem_CadChamado_.setText("Cadastrar Chamado");
        jMenuItem_CadChamado_.setContentAreaFilled(false);
        jMenuItem_CadChamado_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadChamado_ActionPerformed(evt);
            }
        });
        jMenu_Chamados_.add(jMenuItem_CadChamado_);

        jMenuItem_PesqChamado_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqChamado_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqChamado_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqChamado_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqChamado_.setText("Pesquisar Chamado");
        jMenuItem_PesqChamado_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqChamado_ActionPerformed(evt);
            }
        });
        jMenu_Chamados_.add(jMenuItem_PesqChamado_);

        jMenuBar_Principal.add(jMenu_Chamados_);

        jMenu_Situacao_.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Situacao_.setText("Situação");
        jMenu_Situacao_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu_Situacao_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Situacao_ActionPerformed(evt);
            }
        });

        jMenuItem_CadSituacao_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadSituacao_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadSituacao_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadSituacao_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jMenuItem_CadSituacao_.setText("Cadastrar Situação");
        jMenuItem_CadSituacao_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadSituacao_ActionPerformed(evt);
            }
        });
        jMenu_Situacao_.add(jMenuItem_CadSituacao_);

        jMenuItem_PesqSituacao_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqSituacao_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqSituacao_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqSituacao_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqSituacao_.setText("Pesquisar Situação");
        jMenuItem_PesqSituacao_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqSituacao_ActionPerformed(evt);
            }
        });
        jMenu_Situacao_.add(jMenuItem_PesqSituacao_);

        jMenuBar_Principal.add(jMenu_Situacao_);

        jMenu_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        jMenu_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Clientes.setText("Clientes");
        jMenu_Clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadCliente_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadCliente_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadCliente_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadCliente_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_add.png"))); // NOI18N
        jMenuItem_CadCliente_.setText("Cadastrar Cliente");
        jMenuItem_CadCliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadCliente_ActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_CadCliente_);

        jMenuItem_PesqCliente.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqCliente.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqCliente.setText("Pesquisar Cliente");
        jMenuItem_PesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqClienteActionPerformed(evt);
            }
        });
        jMenu_Clientes.add(jMenuItem_PesqCliente);

        jMenuBar_Principal.add(jMenu_Clientes);

        jMenu_Clientes1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu_Clientes1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Clientes1.setText("Empresas");
        jMenu_Clientes1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadEmpresa.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cad_empresa.png"))); // NOI18N
        jMenuItem_CadEmpresa.setText("Cadastrar Empresa");
        jMenuItem_CadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadEmpresaActionPerformed(evt);
            }
        });
        jMenu_Clientes1.add(jMenuItem_CadEmpresa);

        jMenuItem_PesqEmpresa.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqEmpresa.setText("Pesquisar Empresa");
        jMenuItem_PesqEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqEmpresaActionPerformed(evt);
            }
        });
        jMenu_Clientes1.add(jMenuItem_PesqEmpresa);

        jMenuBar_Principal.add(jMenu_Clientes1);

        jMenu_Fornecedores.setBackground(new java.awt.Color(255, 255, 255));
        jMenu_Fornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Fornecedores.setText("Fornecedores");
        jMenu_Fornecedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadFornecedor_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadFornecedor_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadFornecedor_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadFornecedor_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/world_add.png"))); // NOI18N
        jMenuItem_CadFornecedor_.setText("Cadastrar Fornecedor");
        jMenuItem_CadFornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadFornecedor_ActionPerformed(evt);
            }
        });
        jMenu_Fornecedores.add(jMenuItem_CadFornecedor_);

        jMenuItem_PesqFornecedor_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqFornecedor_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqFornecedor_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqFornecedor_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqFornecedor_.setText("Pesquisar Fornecedor");
        jMenuItem_PesqFornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqFornecedor_ActionPerformed(evt);
            }
        });
        jMenu_Fornecedores.add(jMenuItem_PesqFornecedor_);

        jMenuBar_Principal.add(jMenu_Fornecedores);

        jMenu_Produtos.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Produtos.setText("Produtos");
        jMenu_Produtos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadProduto_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadProduto_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadProduto_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadProduto_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/package_add.png"))); // NOI18N
        jMenuItem_CadProduto_.setText("Cadastrar Produto");
        jMenuItem_CadProduto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadProduto_ActionPerformed(evt);
            }
        });
        jMenu_Produtos.add(jMenuItem_CadProduto_);

        jMenuItem_BaixaProduto_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_BaixaProduto_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_BaixaProduto_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_BaixaProduto_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/package_go.png"))); // NOI18N
        jMenuItem_BaixaProduto_.setText("Baixa Produto");
        jMenuItem_BaixaProduto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_BaixaProduto_ActionPerformed(evt);
            }
        });
        jMenu_Produtos.add(jMenuItem_BaixaProduto_);

        jMenuItem_PesqProduto_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqProduto_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqProduto_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqProduto_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqProduto_.setText("Pesquisar Produto");
        jMenuItem_PesqProduto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqProduto_ActionPerformed(evt);
            }
        });
        jMenu_Produtos.add(jMenuItem_PesqProduto_);

        jMenuBar_Principal.add(jMenu_Produtos);

        jMenu_Tecnico1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Tecnico1.setText("Compras");
        jMenu_Tecnico1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadCompra_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadCompra_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadCompra_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadCompra_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carrinho-de-compras (1).png"))); // NOI18N
        jMenuItem_CadCompra_.setText("Cadastrar Compra");
        jMenuItem_CadCompra_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadCompra_ActionPerformed(evt);
            }
        });
        jMenu_Tecnico1.add(jMenuItem_CadCompra_);

        jMenuItem_PesqCompra_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqCompra_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqCompra_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqCompra_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqCompra_.setText("Pesquisar Compra");
        jMenuItem_PesqCompra_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqCompra_ActionPerformed(evt);
            }
        });
        jMenu_Tecnico1.add(jMenuItem_PesqCompra_);

        jMenuBar_Principal.add(jMenu_Tecnico1);

        jMenu_Tecnico.setForeground(new java.awt.Color(255, 255, 255));
        jMenu_Tecnico.setText("Técnico");
        jMenu_Tecnico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem_CadTecnico_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_CadTecnico_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_CadTecnico_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_CadTecnico_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_gray.png"))); // NOI18N
        jMenuItem_CadTecnico_.setText("Cadastrar Técnico");
        jMenuItem_CadTecnico_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadTecnico_ActionPerformed(evt);
            }
        });
        jMenu_Tecnico.add(jMenuItem_CadTecnico_);

        jMenuItem_PesqTecnico_.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem_PesqTecnico_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_PesqTecnico_.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem_PesqTecnico_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/zoom.png"))); // NOI18N
        jMenuItem_PesqTecnico_.setText("Pesquisar Técnico");
        jMenuItem_PesqTecnico_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PesqTecnico_ActionPerformed(evt);
            }
        });
        jMenu_Tecnico.add(jMenuItem_PesqTecnico_);

        jMenuBar_Principal.add(jMenu_Tecnico);

        setJMenuBar(jMenuBar_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Botoes_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_Botoes_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CadFornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadFornecedor_ActionPerformed
        // Objeto da tela
        Fornecedor fornecedor = new Fornecedor(this, true);
        
        //  Centralizando a tela
        fornecedor.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        fornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadFornecedor_ActionPerformed

    private void jMenuItem_PesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqClienteActionPerformed
        // Objeto da tela
        PesqCliente cliente = new PesqCliente(this, true);
        
        //  Centralizando a tela
        cliente.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqClienteActionPerformed

    private void jMenuItem_CadCliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadCliente_ActionPerformed
        //  // Objeto da tela
        Cliente cliente = new Cliente(this, true);
        
        //  Centralizando a tela
        cliente.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadCliente_ActionPerformed

    private void jMenuItem_PesqChamado_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqChamado_ActionPerformed
        //  Objeto da tela
        PesqChamado chamado = new PesqChamado(this, true);
        
        //  Centralizando a tela
        chamado.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        chamado.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqChamado_ActionPerformed

    private void jMenuItem_CadChamado_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadChamado_ActionPerformed
       
       //  Objeto da tela
       Chamado chamado = new Chamado(this, true);
       
       //  Centralizando a tela
       chamado.setLocationRelativeTo(null);
       
       //   Exibindo a tela
       chamado.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem_CadChamado_ActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jButton_CadCompra_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadCompra_ActionPerformed
        // Objeto da tela
        Compra compra = new Compra(this, true);
        
        //  Centralizando a tela
        compra.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        compra.setVisible(true);
    }//GEN-LAST:event_jButton_CadCompra_ActionPerformed

    private void jButton_CriarChamado_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CriarChamado_ActionPerformed
        // Objeto da tela
        Chamado chamado = new Chamado(this, true);
        
        //  Centralizando a tela
        chamado.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        chamado.setVisible(true);
        
        atualiza();
    }//GEN-LAST:event_jButton_CriarChamado_ActionPerformed

    private void jMenuItem_PesqSituacao_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqSituacao_ActionPerformed
        // Objeto da tela
        PesqSituacao pesquisa = new PesqSituacao(this, true);
        
        //  Centralizando a tela
        pesquisa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        pesquisa.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqSituacao_ActionPerformed

    private void jMenuItem_CadSituacao_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadSituacao_ActionPerformed
        //  Objeto da tela
        Situacao situacao = new Situacao(this, true);
        
        //  Centralizando a tela
        situacao.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        situacao.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadSituacao_ActionPerformed

    private void jMenu_Situacao_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Situacao_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_Situacao_ActionPerformed

    private void jButton_CadCliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadCliente_ActionPerformed
        //  Objeto da tela
        Cliente cliente = new Cliente(this, true);
        
        //  Centralizando a tela
        cliente.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        cliente.setVisible(true);
    }//GEN-LAST:event_jButton_CadCliente_ActionPerformed

    private void jButton_CadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadEmpresaActionPerformed
        //  Objeto da tela
        Empresa empresa = new Empresa(this, true);
        
        //  Centralizando a tela
        empresa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        empresa.setVisible(true);
    }//GEN-LAST:event_jButton_CadEmpresaActionPerformed

    private void jMenuItem_CadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadEmpresaActionPerformed
        //  Objeto da tela
        Empresa empresa = new Empresa(this, true);
        
        //  Centralizando a tela
        empresa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        empresa.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadEmpresaActionPerformed

    private void jMenuItem_PesqEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqEmpresaActionPerformed
        // Objeto da Tela
        PesqEmpresa empresa = new PesqEmpresa(this, true);
        
        //  Centralizando a tela
        empresa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        empresa.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqEmpresaActionPerformed

    private void jMenuItem_CadCompra_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadCompra_ActionPerformed
        // Objeto da tela
        Compra compra = new Compra(this, true);
        
        //  Centralizando a tela
        compra.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        compra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadCompra_ActionPerformed

    private void jMenuItem_CadTecnico_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadTecnico_ActionPerformed
        //  Objeto da tela
        Tecnico tecnico = new Tecnico(this, true);
        
        //  Centralizando a tela
        tecnico.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        tecnico.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadTecnico_ActionPerformed

    private void jMenuItem_CadProduto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadProduto_ActionPerformed
        // Objeto da Tela
        Produto produto = new Produto(this, true);
        
        //  Centralizando a tela
        produto.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        produto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CadProduto_ActionPerformed

    private void jButton_BaixaProduto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BaixaProduto_ActionPerformed
        // Objeto da tela
        BaixaProduto baixa = new BaixaProduto(this, true);
        
        //  Centralizando a tela
        baixa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        baixa.setVisible(true);
    }//GEN-LAST:event_jButton_BaixaProduto_ActionPerformed

    private void jMenuItem_BaixaProduto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_BaixaProduto_ActionPerformed
        // Objeto da tela
        BaixaProduto baixa = new BaixaProduto(this, true);
        
        //  Centralizando a tela
        baixa.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        baixa.setVisible(true);
    }//GEN-LAST:event_jMenuItem_BaixaProduto_ActionPerformed

    private void jTable_ChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ChamadoMouseClicked

        new Chamado(this, true, lista.get(jTable_Chamado.getSelectedRow())).setVisible(true);

    }//GEN-LAST:event_jTable_ChamadoMouseClicked

    private void jMenuItem_PesqFornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqFornecedor_ActionPerformed
        // Objeto da Tela
        PesqFornecedor fornecedor = new PesqFornecedor(this, true);
                
        // Centralizando a tela
        fornecedor.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        fornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqFornecedor_ActionPerformed

    private void jMenuItem_PesqProduto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqProduto_ActionPerformed
        // Objeto da Tela
        PesqProduto produto = new PesqProduto(this, true);
        
        //  Centralizando a tela
        produto.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        produto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqProduto_ActionPerformed

    private void jMenuItem_PesqTecnico_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqTecnico_ActionPerformed
        //  Objeto da tela
        PesqTecnico tecnico = new PesqTecnico(this, true);
        
        //  Centralizando a tela
        tecnico.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        tecnico.setVisible(true);
    }//GEN-LAST:event_jMenuItem_PesqTecnico_ActionPerformed

    private void jTable_ChamadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_ChamadoKeyPressed
        
        new Chamado(this, true, lista.get(jTable_Chamado.getSelectedRow())).setVisible(true);
        
    }//GEN-LAST:event_jTable_ChamadoKeyPressed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
        
        //  Atualiza listagem de chamados
        atualiza();
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jMenuItem_PesqCompra_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PesqCompra_ActionPerformed
        
        // Objeto da Tela
        PesqCompra compra = new PesqCompra(this, true);
        
        //  Centralizando a tela
        compra.setLocationRelativeTo(null);
        
        //  Exibindo a tela
        compra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_PesqCompra_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                atualiza();
            }

            private void atualiza() 
            {
                String[] titulos = new String[]{"Número", "Nome"};
                DefaultTableModel dtm = new DefaultTableModel();
                
                
            }// Fim do método atualiza
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BaixaProduto_;
    private javax.swing.JButton jButton_CadCliente_;
    private javax.swing.JButton jButton_CadCompra_;
    private javax.swing.JButton jButton_CadEmpresa;
    private javax.swing.JButton jButton_CriarChamado_;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabel_BaixaProduto;
    private javax.swing.JLabel jLabel_CadCliente;
    private javax.swing.JLabel jLabel_CadCompra;
    private javax.swing.JLabel jLabel_CadEmpresa;
    private javax.swing.JLabel jLabel_ChamadoVencimento1;
    private javax.swing.JLabel jLabel_CriarChamado;
    private javax.swing.JLabel jLabel_Data;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar_Principal;
    private javax.swing.JMenuItem jMenuItem_BaixaProduto_;
    private javax.swing.JMenuItem jMenuItem_CadChamado_;
    private javax.swing.JMenuItem jMenuItem_CadCliente_;
    private javax.swing.JMenuItem jMenuItem_CadCompra_;
    private javax.swing.JMenuItem jMenuItem_CadEmpresa;
    private javax.swing.JMenuItem jMenuItem_CadFornecedor_;
    private javax.swing.JMenuItem jMenuItem_CadProduto_;
    private javax.swing.JMenuItem jMenuItem_CadSituacao_;
    private javax.swing.JMenuItem jMenuItem_CadTecnico_;
    private javax.swing.JMenuItem jMenuItem_PesqChamado_;
    private javax.swing.JMenuItem jMenuItem_PesqCliente;
    private javax.swing.JMenuItem jMenuItem_PesqCompra_;
    private javax.swing.JMenuItem jMenuItem_PesqEmpresa;
    private javax.swing.JMenuItem jMenuItem_PesqFornecedor_;
    private javax.swing.JMenuItem jMenuItem_PesqProduto_;
    private javax.swing.JMenuItem jMenuItem_PesqSituacao_;
    private javax.swing.JMenuItem jMenuItem_PesqTecnico_;
    private javax.swing.JMenu jMenu_Chamados_;
    private javax.swing.JMenu jMenu_Clientes;
    private javax.swing.JMenu jMenu_Clientes1;
    private javax.swing.JMenu jMenu_Fornecedores;
    private javax.swing.JMenu jMenu_Produtos;
    private javax.swing.JMenu jMenu_Situacao_;
    private javax.swing.JMenu jMenu_Tecnico;
    private javax.swing.JMenu jMenu_Tecnico1;
    private javax.swing.JPanel jPanel_Botoes_;
    private javax.swing.JPanel jPanel_Chamados;
    private javax.swing.JPanel jPanel_Principal_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Chamado;
    // End of variables declaration//GEN-END:variables
}
