/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class BaixaProduto extends javax.swing.JDialog {

    /**
     * Creates new form BaixaProduto
     */
    
    //  Iniciando baixa
     models.BaixaProduto baixa;
    
    public BaixaProduto(java.awt.Frame parent, boolean modal, models.BaixaProduto baixa) {
        super(parent, modal);
        initComponents();
        
        this.baixa = baixa;
        
        setLocationRelativeTo(null);
        atualizaComboBox(); 
        atualizaDados();
        
    }// Fim do construtor BaixaProduto 
     
    public BaixaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //  Preenchendo os Combo Box
        atualizaComboBox();
        
    }// Fim do construtor BaixaProduto
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        List produto = new LinkedList();
        produto.add("Selecione");
        produto.addAll(DAO.consulta(models.Produto.class, ""));
        jComboBox_Produto_.setModel(new DefaultComboBoxModel<>(produto.toArray()));
        
        List chamado = new LinkedList();
        chamado.add("Selecione");
        chamado.addAll(DAO.consulta(models.Chamado.class, ""));
        jComboBox_Chamado_.setModel(new DefaultComboBoxModel<>(chamado.toArray()));
        
        List cliente = new LinkedList();
        cliente.add("Selecione");
        cliente.addAll(DAO.consulta(models.Cliente.class, ""));
        jComboBox_Cliente.setModel(new DefaultComboBoxModel<>(cliente.toArray()));
    }// Fim do método atualizaComboBox
    
    private void atualizaDados()
    {
        
        jComboBox_Produto_.setSelectedItem(baixa.getIdProduto());
        jTextField_Quantidade_.setText(baixa.getQuantidade() + "");
        jComboBox_Chamado_.setSelectedItem(baixa.getIdChamado());
        jComboBox_Cliente.setSelectedItem(baixa.getIdCliente());
        
    }// Fim do método atualizaDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_baixaProduto = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jLabel_Numero = new javax.swing.JLabel();
        jComboBox_Produto_ = new javax.swing.JComboBox<>();
        jLabel_Produto = new javax.swing.JLabel();
        jTextField_Quantidade_ = new javax.swing.JTextField();
        jLabel_Quantidade = new javax.swing.JLabel();
        jComboBox_Chamado_ = new javax.swing.JComboBox<>();
        jLabel_Chamado = new javax.swing.JLabel();
        jComboBox_Cliente = new javax.swing.JComboBox<>();
        jLabel_Cliente = new javax.swing.JLabel();
        jButton_Sair_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Salvar_ = new javax.swing.JButton();
        jLabel_Aviso = new javax.swing.JLabel();
        jLabel_Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baixa do Estoque");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_baixaProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_baixaProduto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_baixaProduto.setText("BAIXA PRODUTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_baixaProduto)
                .addContainerGap(601, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_baixaProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jComboBox_Produto_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Produto_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Produto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Produto_ActionPerformed(evt);
            }
        });

        jLabel_Produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Produto.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Produto.setText("Produto");

        jTextField_Quantidade_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Quantidade_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Quantidade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Quantidade_ActionPerformed(evt);
            }
        });

        jLabel_Quantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Quantidade.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Quantidade.setText("Quantidade");

        jComboBox_Chamado_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Chamado_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Chamado_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Chamado_ActionPerformed(evt);
            }
        });

        jLabel_Chamado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Chamado.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Chamado.setText("Chamado");

        jComboBox_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClienteActionPerformed(evt);
            }
        });

        jLabel_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Cliente.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Cliente.setText("Cliente");

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jLabel_Aviso.setText("A QUANTIDADE INFORMADA SERÁ SUBTRAÍDA DO ESTOQUE DO PRODUTO SELECIONADO AUTOMATICAMENTE.");

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Chamado)
                                    .addComponent(jComboBox_Chamado_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Cliente)
                                    .addComponent(jComboBox_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_Aviso)
                            .addComponent(jLabel_Aviso1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Salvar_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Numero)
                            .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Produto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBox_Produto_, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Quantidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Quantidade))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Produto)
                        .addGap(36, 36, 36))
                    .addComponent(jComboBox_Produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Quantidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBox_Chamado_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Chamado)
                                .addComponent(jLabel_Cliente))
                            .addGap(36, 36, 36)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Aviso1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Aviso)))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jComboBox_Produto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Produto_ActionPerformed

    }//GEN-LAST:event_jComboBox_Produto_ActionPerformed

    private void jTextField_Quantidade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Quantidade_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Quantidade_ActionPerformed

    private void jComboBox_Chamado_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Chamado_ActionPerformed

    }//GEN-LAST:event_jComboBox_Chamado_ActionPerformed

    private void jComboBox_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ClienteActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            //  Atualizando estoque do produto
            models.Produto produto = (models.Produto) jComboBox_Produto_.getSelectedItem();
            produto.setEstoque(produto.getEstoque() + baixa.getQuantidade());
            
            //  Deletando
            DAO.remover(baixa);
            
            //  Mensagem de Salvo
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
            //  Limpa Campos
            baixa = new models.BaixaProduto();
            atualizaDados();
            
        }catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, "ERRO:" + s);
            }// Fim do try-catch
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
        
        try
        {
            //  Instanciando objetos
            baixa = new models.BaixaProduto();
            models.Produto produto = (models.Produto) jComboBox_Produto_.getSelectedItem();

            //  Selecionando os campos a serem salvos
            baixa.setIdProduto(produto);
            baixa.setQuantidade(Integer.parseInt(jTextField_Quantidade_.getText()));
            baixa.setIdChamado((models.Chamado) jComboBox_Chamado_.getSelectedItem());
            baixa.setIdCliente((models.Cliente) jComboBox_Cliente.getSelectedItem());

            //  Chamando método para gravar no banco
            DAO.salvar(baixa);
            
            //  Atualizando estoque do produto
            produto.setEstoque(produto.getEstoque() - baixa.getQuantidade());
            DAO.editar(produto);
            
            //  Mensagem de Salvo
            JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");
            
            //  Limpa Campos
            baixa = new models.BaixaProduto();
            atualizaDados();
            
        } catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, "ERRO:" + s);
            }// Fim do try-catch
        
        
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaixaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaixaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaixaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaixaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BaixaProduto dialog = new BaixaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JComboBox<Object> jComboBox_Chamado_;
    private javax.swing.JComboBox<Object> jComboBox_Cliente;
    private javax.swing.JComboBox<Object> jComboBox_Produto_;
    private javax.swing.JLabel jLabel_Aviso;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_Chamado;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_Quantidade;
    private javax.swing.JLabel jLabel_baixaProduto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Numero_;
    private javax.swing.JTextField jTextField_Quantidade_;
    // End of variables declaration//GEN-END:variables
}
