/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Empresacliente;
import models.SituacaoChamado;
import models.Tipo;
import persistence.DAO;
import telas.Principal;

/**
 *
 * @author Altair Mateus T Alencastro
 */

public class Chamado extends javax.swing.JDialog {

    /**
     * Creates new form Chamado
     */
    
    //  Iniciando chamado
    models.Chamado chamado;
    
    public Chamado(java.awt.Frame parent, boolean modal, models.Chamado chamado) {
        super(parent, modal);
        initComponents();
        
        this.chamado = chamado;
        
        setLocationRelativeTo(null);
        atualizaComboBox(); 
        atualizaDados();
            
    }// Fim do Construtor Chamado
    
    public Chamado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        atualizaComboBox();
     
    }// Fim do Construtor Chamado
    
    private void atualizaDados()
    {
        jTextField_Nome_.setText(chamado.getNome());
        jTextArea_DescCliente.setText(chamado.getDescricaoCliente());
        jDateChooser_Abertura_.setDate(chamado.getDataAbertura());
        jDateChooser_Vencimento_.setDate(chamado.getVencimento());
        jComboBox_Tipo.setSelectedItem(chamado.getIdTipo());
        jComboBox_Cliente_.setSelectedItem(chamado.getIdCliente());
        jComboBox_Prioridade.setSelectedItem(chamado.getIdPrioridade());
        jTextArea_DescTecnico.setText(chamado.getDescricaoTecnico());
        jComboBox_TecnicoResp_.setSelectedItem(chamado.getIdTecnico());
        jComboBox_Situacao_.setSelectedItem(chamado.getIdSituacao());
        jComboBox_Empresa.setSelectedItem(chamado.getIdEmpresa());
        
    }// Fim do método atualizaDados
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        
        List tipos = new LinkedList();
        tipos.add("Selecione");
        tipos.addAll(DAO.consulta(Tipo.class, ""));
        jComboBox_Tipo.setModel(new DefaultComboBoxModel(tipos.toArray()));
        
        List cliente = new LinkedList();
        cliente.add("Selecione");
        cliente.addAll(DAO.consulta(models.Cliente.class, ""));
        jComboBox_Cliente_.setModel(new DefaultComboBoxModel<>(cliente.toArray()));
        
        List prioridade = new LinkedList();
        prioridade.add("Selecione");
        prioridade.addAll(DAO.consulta(models.Prioridade.class, ""));
        jComboBox_Prioridade.setModel(new DefaultComboBoxModel<>(prioridade.toArray()));
        
        List tecnico = new LinkedList();
        tecnico.add("Selecione");
        tecnico.addAll(DAO.consulta(models.Tecnico.class, ""));
        jComboBox_TecnicoResp_.setModel(new DefaultComboBoxModel<>(tecnico.toArray()));
        
        List situacao = new LinkedList();
        situacao.add("Selecione");
        situacao.addAll(DAO.consulta(SituacaoChamado.class, ""));
        jComboBox_Situacao_.setModel(new DefaultComboBoxModel<>(situacao.toArray()));
        
        List empresa = new LinkedList();
        empresa.add("Selecione");
        empresa.addAll(DAO.consulta(Empresacliente.class, ""));
        jComboBox_Empresa.setModel(new DefaultComboBoxModel<>(empresa.toArray()));
        
    }// Fim do método
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Chamado = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jLabel_Numero = new javax.swing.JLabel();
        jTextField_Nome_ = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_DataAbertura = new javax.swing.JLabel();
        jDateChooser_Abertura_ = new com.toedter.calendar.JDateChooser();
        jLabel_DescCliente = new javax.swing.JLabel();
        jLabel_DescTecnico = new javax.swing.JLabel();
        jDateChooser_Vencimento_ = new com.toedter.calendar.JDateChooser();
        jLabel_Vencimento = new javax.swing.JLabel();
        jComboBox_Tipo = new javax.swing.JComboBox<>();
        jLabel_Tipo = new javax.swing.JLabel();
        jComboBox_Cliente_ = new javax.swing.JComboBox<>();
        jLabel_Cliente = new javax.swing.JLabel();
        jComboBox_Prioridade = new javax.swing.JComboBox<>();
        jLabel_Prioridade = new javax.swing.JLabel();
        jComboBox_TecnicoResp_ = new javax.swing.JComboBox<>();
        jLabel_TecnicoResp = new javax.swing.JLabel();
        jComboBox_Situacao_ = new javax.swing.JComboBox<>();
        jLabel_Situacao = new javax.swing.JLabel();
        jButton_Sair_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Salvar_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DescCliente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_DescTecnico = new javax.swing.JTextArea();
        jLabel_Aviso = new javax.swing.JLabel();
        jComboBox_Empresa = new javax.swing.JComboBox<>();
        jLabel_Empresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar, Editar ou Deletar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Chamado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Chamado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Chamado.setText("CHAMADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Chamado)
                .addContainerGap(655, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Chamado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jTextField_Nome_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nome_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nome_ActionPerformed(evt);
            }
        });

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Nome.setText("Nome");

        jLabel_DataAbertura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_DataAbertura.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_DataAbertura.setText("Data Abertura");

        jDateChooser_Abertura_.setDateFormatString("d'/'M'/'y");

        jLabel_DescCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DescCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DescCliente.setText("Descrição do Cliente");

        jLabel_DescTecnico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DescTecnico.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DescTecnico.setText("Descrição do Técnico");

        jDateChooser_Vencimento_.setDateFormatString("d'/'M'/'y");

        jLabel_Vencimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Vencimento.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Vencimento.setText("Vencimento");

        jComboBox_Tipo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Tipo.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoActionPerformed(evt);
            }
        });

        jLabel_Tipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Tipo.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Tipo.setText("Tipo");

        jComboBox_Cliente_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Cliente_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Cliente_ActionPerformed(evt);
            }
        });

        jLabel_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Cliente.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Cliente.setText("Cliente/Solicitante");

        jComboBox_Prioridade.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Prioridade.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Prioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PrioridadeActionPerformed(evt);
            }
        });

        jLabel_Prioridade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Prioridade.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Prioridade.setText("Prioridade");

        jComboBox_TecnicoResp_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_TecnicoResp_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_TecnicoResp_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TecnicoResp_ActionPerformed(evt);
            }
        });

        jLabel_TecnicoResp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_TecnicoResp.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_TecnicoResp.setText("Técnico Resp");

        jComboBox_Situacao_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Situacao_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Situacao_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Situacao_ActionPerformed(evt);
            }
        });

        jLabel_Situacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Situacao.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Situacao.setText("Situação");

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jTextArea_DescCliente.setColumns(20);
        jTextArea_DescCliente.setRows(5);
        jScrollPane1.setViewportView(jTextArea_DescCliente);

        jTextArea_DescTecnico.setColumns(20);
        jTextArea_DescTecnico.setRows(5);
        jScrollPane2.setViewportView(jTextArea_DescTecnico);

        jLabel_Aviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        jComboBox_Empresa.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Empresa.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EmpresaActionPerformed(evt);
            }
        });

        jLabel_Empresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Empresa.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Empresa.setText("Empresa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DescTecnico)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Numero)
                            .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nome)
                            .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_TecnicoResp_, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Situacao)
                                .addComponent(jComboBox_Situacao_, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TecnicoResp))
                            .addGap(141, 141, 141))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_DescCliente)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_Empresa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox_Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_Salvar_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser_Vencimento_, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_Cliente)
                                        .addComponent(jLabel_Vencimento)
                                        .addComponent(jComboBox_Cliente_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser_Abertura_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_DataAbertura)
                                        .addComponent(jLabel_Tipo)
                                        .addComponent(jComboBox_Tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Prioridade)
                                        .addComponent(jComboBox_Prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel_Aviso, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nome)
                            .addComponent(jLabel_DataAbertura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Nome_, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDateChooser_Abertura_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Tipo)
                            .addComponent(jLabel_Vencimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Cliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Prioridade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DescCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jDateChooser_Vencimento_, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DescTecnico)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_TecnicoResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TecnicoResp_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Situacao_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel_Situacao)
                                        .addGap(36, 36, 36))))
                            .addComponent(jScrollPane2))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Empresa)
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Aviso)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jTextField_Nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_ActionPerformed

    private void jComboBox_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoActionPerformed

    }//GEN-LAST:event_jComboBox_TipoActionPerformed

    private void jComboBox_PrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_PrioridadeActionPerformed

    private void jComboBox_TecnicoResp_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TecnicoResp_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TecnicoResp_ActionPerformed

    private void jComboBox_Situacao_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Situacao_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Situacao_ActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
        
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            DAO.remover(chamado);

            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
            //  Limpa Campos
            chamado = new models.Chamado();
            atualizaDados();
            
            //  Atualizando tela principal de chamados
            Principal p = new Principal();
            
        } catch(Exception s)
                {
                    JOptionPane.showMessageDialog(this, "ERRO:" + s);
                }// fim do try-catch
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
        try
        {
            //  Instanciando objeto da classe BaixaProduto
            if(chamado == null)
            chamado = new models.Chamado();
            
            Date data_vencimento = jDateChooser_Vencimento_.getDate();
            Date data_abertura = jDateChooser_Abertura_.getDate();
            Date data_atual = new Date(System.currentTimeMillis());
            models.Tipo tipo = (models.Tipo) jComboBox_Tipo.getSelectedItem();

            //  Selecionando os campos a serem salvos
            chamado.setNome(jTextField_Nome_.getText());
            chamado.setDescricaoCliente(jTextArea_DescCliente.getText());
            chamado.setDataAbertura(data_abertura);
            chamado.setVencimento(data_vencimento);
            chamado.setIdTipo(tipo);
            chamado.setIdCliente((models.Cliente) jComboBox_Cliente_.getSelectedItem());
            chamado.setIdPrioridade((models.Prioridade) jComboBox_Prioridade.getSelectedItem());
            chamado.setDescricaoTecnico(jTextArea_DescTecnico.getText());
            chamado.setIdTecnico((models.Tecnico) jComboBox_TecnicoResp_.getSelectedItem());
            chamado.setIdSituacao((models.SituacaoChamado) jComboBox_Situacao_.getSelectedItem());
            chamado.setIdEmpresa((models.Empresacliente) jComboBox_Empresa.getSelectedItem());
            
            
            
            if(data_vencimento.before(data_abertura))
            {
                JOptionPane.showMessageDialog(this, "DATA DE VENCIMENTO NÃO PODE SER ANTERIOR A DE ABERTURA", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            } else if(data_abertura.after(data_atual))
                    {
                        JOptionPane.showMessageDialog(this, "DATA DE ABERTURA NÃO PODE SER POSTERIOR A DATA ATUAL", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    } else
                            {
                                //  Chamando método para gravar no banco
                                DAO.editar(chamado); 

                                JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");

                                //  Limpa Campos
                                chamado = new models.Chamado();
                                atualizaDados();
                                atualizaComboBox();

                                //  Atualizando tela principal de chamados
                                Principal p = new Principal();
                                }// Fim dos blocos de condições if-else
               
        } catch(Exception s)
                {
               
                    //JOptionPane.showMessageDialog(this, s);
                    JOptionPane.showMessageDialog(null, "Revise os dados obrigatórios\n " + s, "Erro", JOptionPane.ERROR_MESSAGE);
                    
                }// Fim do try-catch
        
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jComboBox_Cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Cliente_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Cliente_ActionPerformed

    private void jComboBox_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Chamado dialog = new Chamado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JComboBox<Object> jComboBox_Cliente_;
    private javax.swing.JComboBox<Object> jComboBox_Empresa;
    private javax.swing.JComboBox<Object> jComboBox_Prioridade;
    private javax.swing.JComboBox<Object> jComboBox_Situacao_;
    private javax.swing.JComboBox<Object> jComboBox_TecnicoResp_;
    private javax.swing.JComboBox<Object> jComboBox_Tipo;
    private com.toedter.calendar.JDateChooser jDateChooser_Abertura_;
    private com.toedter.calendar.JDateChooser jDateChooser_Vencimento_;
    private javax.swing.JLabel jLabel_Aviso;
    private javax.swing.JLabel jLabel_Chamado;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_DataAbertura;
    private javax.swing.JLabel jLabel_DescCliente;
    private javax.swing.JLabel jLabel_DescTecnico;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_Prioridade;
    private javax.swing.JLabel jLabel_Situacao;
    private javax.swing.JLabel jLabel_TecnicoResp;
    private javax.swing.JLabel jLabel_Tipo;
    private javax.swing.JLabel jLabel_Vencimento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_DescCliente;
    private javax.swing.JTextArea jTextArea_DescTecnico;
    private javax.swing.JTextField jTextField_Nome_;
    private javax.swing.JTextField jTextField_Numero_;
    // End of variables declaration//GEN-END:variables
}
