/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Empresacliente;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Cliente extends javax.swing.JDialog {

    /**
     * Creates new form Cliente
     */
    
    models.Cliente cliente;
    
    public Cliente(java.awt.Frame parent, boolean modal, models.Cliente cliente) {
        super(parent, modal);
        initComponents();
        
        this.cliente = cliente;
        
        setLocationRelativeTo(null);
        atualizaComboBox(); 
        atualizaDados();
    }// Fim do construtor
            
    public Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //  Chamando método para preecnher combobox
        atualizaComboBox();
    }// Fim do construtor
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        
        List empresa = new LinkedList();
        empresa.add("Selecione");
        empresa.addAll(DAO.consulta(models.Empresacliente.class, ""));
        jComboBox_Empresa_.setModel(new DefaultComboBoxModel<>(empresa.toArray())); 
        
    }// Fim do método atualizaComboBox
    
    private void atualizaDados()
    {
        jTextField_Nome_.setText(cliente.getNome());
        jTextField_Telefone_.setText(cliente.getTelefone());
        jTextField_CpfCnpj_.setText(cliente.getCpfCnpj());
        jTextField_Email_.setText(cliente.getEmail());
        jTextField_AvRua_.setText(cliente.getAvRua());
        jTextField_NumeroLog_.setText(cliente.getNumero());
        jTextField_Bairro_.setText(cliente.getBairro());
        jTextField_Cidade_.setText(cliente.getCidade());
        jTextField_UF.setText(cliente.getUf());
        jComboBox_Empresa_.setSelectedItem(cliente.getIdEmpresa());
        
    }// Fim do método atualizaDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Cliente = new javax.swing.JLabel();
        jLabel_Numero = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jButton_Salvar_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jTextField_Nome_ = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_CpfCnpj_ = new javax.swing.JTextField();
        jLabel_CpfCnpj = new javax.swing.JLabel();
        jTextField_Telefone_ = new javax.swing.JTextField();
        jLabel_Telefone = new javax.swing.JLabel();
        jTextField_Email_ = new javax.swing.JTextField();
        jTextField_Cidade_ = new javax.swing.JTextField();
        jLabel_Cidade = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_AvRua_ = new javax.swing.JTextField();
        jLabel_AvRua = new javax.swing.JLabel();
        jTextField_NumeroLog_ = new javax.swing.JTextField();
        jLabel_NumeroLog = new javax.swing.JLabel();
        jTextField_Bairro_ = new javax.swing.JTextField();
        jLabel_Bairro = new javax.swing.JLabel();
        jTextField_UF = new javax.swing.JTextField();
        jLabel_UF = new javax.swing.JLabel();
        jLabel_Bairro1 = new javax.swing.JLabel();
        jComboBox_Empresa_ = new javax.swing.JComboBox<>();
        jLabel_Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar, Editar ou Deletar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Cliente.setText("CLIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Cliente)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Cliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setText("Número");

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jTextField_Nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nome_ActionPerformed(evt);
            }
        });

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Nome.setText("Nome");

        jTextField_CpfCnpj_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CpfCnpj_ActionPerformed(evt);
            }
        });

        jLabel_CpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CpfCnpj.setText("CPF");

        jTextField_Telefone_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Telefone_ActionPerformed(evt);
            }
        });

        jLabel_Telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Telefone.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Telefone.setText("Telefone");

        jTextField_Email_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email_ActionPerformed(evt);
            }
        });

        jTextField_Cidade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cidade_ActionPerformed(evt);
            }
        });

        jLabel_Cidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Cidade.setText("Cidade");

        jLabel_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Email.setText("E-mail");

        jTextField_AvRua_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AvRua_ActionPerformed(evt);
            }
        });

        jLabel_AvRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_AvRua.setText("Av/Rua");

        jTextField_NumeroLog_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumeroLog_ActionPerformed(evt);
            }
        });

        jLabel_NumeroLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_NumeroLog.setText("Número Log");

        jTextField_Bairro_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Bairro_ActionPerformed(evt);
            }
        });

        jLabel_Bairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Bairro.setText("Bairro");

        jTextField_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UFActionPerformed(evt);
            }
        });

        jLabel_UF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_UF.setText("UF");

        jLabel_Bairro1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Bairro1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Bairro1.setText("Empresa");

        jComboBox_Empresa_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Empresa_ActionPerformed(evt);
            }
        });

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Numero)
                            .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nome)
                            .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CpfCnpj)
                            .addComponent(jTextField_CpfCnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Telefone)
                            .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cidade)
                            .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_AvRua))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_NumeroLog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_NumeroLog_)
                                        .addGap(43, 43, 43))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox_Empresa_, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Bairro)
                            .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_UF)
                            .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Bairro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_Aviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_CpfCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CpfCnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_AvRua)
                            .addComponent(jLabel_NumeroLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NumeroLog_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel_Bairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Bairro1)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_UF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_Empresa_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Aviso1)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
         
        try
        {
            //  Instanciando objetos
            if(cliente==null)
            cliente = new models.Cliente();

            //  Selecionando os campos a serem salvos
            cliente.setNome(jTextField_Nome_.getText());
            cliente.setCpfCnpj(jTextField_CpfCnpj_.getText());
            cliente.setTelefone(jTextField_Telefone_.getText());
            cliente.setEmail(jTextField_Email_.getText());
            cliente.setCidade(jTextField_Cidade_.getText());
            cliente.setAvRua(jTextField_AvRua_.getText());
            cliente.setNumero(jTextField_NumeroLog_.getText());
            cliente.setBairro(jTextField_Bairro_.getText());
            cliente.setUf(jTextField_UF.getText());
            cliente.setIdEmpresa((models.Empresacliente) jComboBox_Empresa_.getSelectedItem());

            //  Chamando método para gravar no banco
            DAO.editar(cliente);
            
            JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");
            
            //  Limpa Campos
            cliente = new models.Cliente();
            atualizaDados();
            atualizaComboBox();
            
        } catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, s);
            }// Fim do try-catch
        
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            
            DAO.remover(cliente);
            
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
            //  Limpa campos
            cliente = new models.Cliente();
            atualizaDados();
            
        }catch(Exception s)
                {
                    JOptionPane.showMessageDialog(this, "ERRO:" + s);
                }// fim do try-catch
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jTextField_Nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_ActionPerformed

    private void jTextField_CpfCnpj_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CpfCnpj_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CpfCnpj_ActionPerformed

    private void jTextField_Telefone_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Telefone_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Telefone_ActionPerformed

    private void jTextField_Email_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email_ActionPerformed

    private void jTextField_Cidade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cidade_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cidade_ActionPerformed

    private void jTextField_AvRua_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AvRua_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvRua_ActionPerformed

    private void jTextField_NumeroLog_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeroLog_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeroLog_ActionPerformed

    private void jTextField_Bairro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Bairro_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Bairro_ActionPerformed

    private void jTextField_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UFActionPerformed

    private void jComboBox_Empresa_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Empresa_ActionPerformed

    }//GEN-LAST:event_jComboBox_Empresa_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente dialog = new Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JComboBox<Object> jComboBox_Empresa_;
    private javax.swing.JLabel jLabel_AvRua;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_Bairro;
    private javax.swing.JLabel jLabel_Bairro1;
    private javax.swing.JLabel jLabel_Cidade;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_CpfCnpj;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_NumeroLog;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JLabel jLabel_UF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_AvRua_;
    private javax.swing.JTextField jTextField_Bairro_;
    private javax.swing.JTextField jTextField_Cidade_;
    private javax.swing.JTextField jTextField_CpfCnpj_;
    private javax.swing.JTextField jTextField_Email_;
    private javax.swing.JTextField jTextField_Nome_;
    private javax.swing.JTextField jTextField_NumeroLog_;
    private javax.swing.JTextField jTextField_Numero_;
    private javax.swing.JTextField jTextField_Telefone_;
    private javax.swing.JTextField jTextField_UF;
    // End of variables declaration//GEN-END:variables
}
