/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Produto;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Compra extends javax.swing.JDialog {

    /**
     * Creates new form Compra
     */
    
    //  Iniciando compra
    models.Compra compra;
            
    public Compra(java.awt.Frame parent, boolean modal, models.Compra compra) {
        super(parent, modal);
        initComponents();
        
        this.compra = compra;
        
        setLocationRelativeTo(null);
        atualizaComboBox(); 
        atualizaDados();
        
    }// Fim do construtor Compra
    
    public Compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //  Preenchimento dos jComboBox
        atualizaComboBox();
        
    }// Fim do construtor Compra
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        List fornecedor = new LinkedList();
        fornecedor.add("Selecione");
        fornecedor.addAll(DAO.consulta(models.Fornecedor.class, ""));
        jComboBox_Fornecedor_.setModel(new DefaultComboBoxModel<>(fornecedor.toArray()));
        
        List produto = new LinkedList();
        produto.add("Selecione");
        produto.addAll(DAO.consulta(models.Produto.class, ""));
        jComboBox_Produto_.setModel(new DefaultComboBoxModel<>(produto.toArray()));
        
    }// Fim do método atualizaComboBox
    
    private void atualizaDados()
    {
        jDateChooser_DataCompra_.setDate(compra.getDataCompra());
        jComboBox_Fornecedor_.setSelectedItem(compra.getIdFornecedor());
        jTextField_Valor_.setText(compra.getValor()+"");
        jComboBox_Produto_.setSelectedItem(compra.getIdProduto());
        jTextField_Quantidade_.setText(compra.getQuantidade() + "");
        
    }// Fim do método atualizaDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Compra = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jLabel_Numero = new javax.swing.JLabel();
        jDateChooser_DataCompra_ = new com.toedter.calendar.JDateChooser();
        jLabel_DataCompra = new javax.swing.JLabel();
        jLabel_Produto = new javax.swing.JLabel();
        jComboBox_Produto_ = new javax.swing.JComboBox<>();
        jTextField_Valor_ = new javax.swing.JTextField();
        jLabel_Valor = new javax.swing.JLabel();
        jComboBox_Fornecedor_ = new javax.swing.JComboBox<>();
        jLabel_Fornecedor = new javax.swing.JLabel();
        jButton_Salvar_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jTextField_Quantidade_ = new javax.swing.JTextField();
        jLabel_Quantidade = new javax.swing.JLabel();
        jLabel_Aviso1 = new javax.swing.JLabel();
        jLabel_Aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar, Editar ou Deletar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Compra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Compra.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Compra.setText("COMPRA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Compra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Compra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jDateChooser_DataCompra_.setDateFormatString("dd/MM/yyyy");

        jLabel_DataCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_DataCompra.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_DataCompra.setText("Data Compra");

        jLabel_Produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Produto.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Produto.setText("Produto");

        jComboBox_Produto_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Produto_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Produto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Produto_ActionPerformed(evt);
            }
        });

        jTextField_Valor_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Valor_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Valor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Valor_ActionPerformed(evt);
            }
        });

        jLabel_Valor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Valor.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Valor.setText("Valor");

        jComboBox_Fornecedor_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Fornecedor_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Fornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Fornecedor_ActionPerformed(evt);
            }
        });

        jLabel_Fornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Fornecedor.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Fornecedor.setText("Fornecedor");

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jTextField_Quantidade_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Quantidade_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Quantidade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Quantidade_ActionPerformed(evt);
            }
        });

        jLabel_Quantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Quantidade.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Quantidade.setText("Quantidade");

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        jLabel_Aviso.setText("A QUANTIDADE INFORMADA SERÁ ADICIONADA NO ESTOQUE DO PRODUTO SELECIONADO AUTOMATICAMENTE.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Numero))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_DataCompra)
                                    .addComponent(jDateChooser_DataCompra_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Valor_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Valor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Quantidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Quantidade))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Produto_, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_Fornecedor_, 0, 319, Short.MAX_VALUE)
                                .addGap(113, 113, 113))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Fornecedor)
                                    .addComponent(jLabel_Produto))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Aviso)
                            .addComponent(jLabel_Aviso1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Salvar_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Numero)
                    .addComponent(jLabel_DataCompra)
                    .addComponent(jLabel_Produto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_Produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDateChooser_DataCompra_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Valor_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Quantidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Valor)
                                    .addComponent(jLabel_Quantidade))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Fornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Fornecedor_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addComponent(jLabel_Aviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Aviso)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jComboBox_Produto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Produto_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Produto_ActionPerformed

    private void jTextField_Valor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Valor_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Valor_ActionPerformed

    private void jComboBox_Fornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Fornecedor_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Fornecedor_ActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
        
        try
        {
            //  Instanciando objetos
            if(compra == null)
            compra =  new models.Compra();
            Produto produto = (models.Produto) jComboBox_Produto_.getSelectedItem();
            
            //  Formatando entrada de valores da compra para o padrão do mysql
            String valor_entrada = jTextField_Valor_.getText();
            double valor = Double.parseDouble(valor_entrada.replace(".","").replace(",", "."));
            
            int qtd = Integer.parseInt(jTextField_Quantidade_.getText());
            

            //  Selecionando os campos a serem salvos
            compra.setDataCompra(jDateChooser_DataCompra_.getDate());
            compra.setIdProduto(produto);
            compra.setValor(valor);
            compra.setIdFornecedor((models.Fornecedor) jComboBox_Fornecedor_.getSelectedItem());
            compra.setQuantidade(qtd);

             if(qtd == 0)
            {
                JOptionPane.showMessageDialog(this, "QUANTIDADE NÃO PODE SER IGUAL A ZERO", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            } else
                {
                    //  Chamando método para gravar no banco
                    DAO.editar(compra);

                    //  Atualizando estoque do produto
                    produto.setEstoque(produto.getEstoque() + compra.getQuantidade());
                    DAO.editar(produto);

                    //  Mensagem de Salvo
                    JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");

                    //  Limpa Campos
                    compra = new models.Compra();
                    atualizaDados();
                }// Fim do bloco de condição if-else
            
            
        } catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, s);
            }// Fim do try-catch
        
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            int qtd = Integer.parseInt(jTextField_Quantidade_.getText());
            Produto produto = (models.Produto) jComboBox_Produto_.getSelectedItem();
            
            DAO.remover(compra);
            
            //  Atualizando estoque do produto            
            produto.setEstoque(produto.getEstoque() - qtd);            
            DAO.editar(produto);
                    
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
        }catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, s);
            }// Fim do try-catch
        
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jTextField_Quantidade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Quantidade_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Quantidade_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Compra dialog = new Compra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JComboBox<Object> jComboBox_Fornecedor_;
    private javax.swing.JComboBox<Object> jComboBox_Produto_;
    private com.toedter.calendar.JDateChooser jDateChooser_DataCompra_;
    private javax.swing.JLabel jLabel_Aviso;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_Compra;
    private javax.swing.JLabel jLabel_DataCompra;
    private javax.swing.JLabel jLabel_Fornecedor;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_Quantidade;
    private javax.swing.JLabel jLabel_Valor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Numero_;
    private javax.swing.JTextField jTextField_Quantidade_;
    private javax.swing.JTextField jTextField_Valor_;
    // End of variables declaration//GEN-END:variables
}
