/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Empresacliente;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Empresa extends javax.swing.JDialog {

    /**
     * Creates new form Empresa
     */
    
    Empresacliente empresa;
    
    public Empresa(java.awt.Frame parent, boolean modal, models.Empresacliente empresa) {
        super(parent, modal);
        initComponents();
        
        this.empresa = empresa;
        
        setLocationRelativeTo(null);
        atualizaDados();
        
    }// Fim do construtor public Empresa
    
    public Empresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }// Fim do construtor public Empresa
    
    private void atualizaDados()
    {
        jTextField_Nome_.setText(empresa.getNome());
        jTextField_Telefone_.setText(empresa.getTelefone());
        jTextField_Cnpj_.setText(empresa.getCnpj());
        jTextField_Ie_.setText(empresa.getIe());
        jTextField_Email_.setText(empresa.getEmail());
        jTextField_AvRua_.setText(empresa.getAvRua());
        jTextField_NumeroLog_.setText(empresa.getNumero());
        jTextField_Bairro_.setText(empresa.getBairro());
        jTextField_Cidade_.setText(empresa.getCidade());
        jTextField_UF.setText(empresa.getUf());
        
    }// Fim do método atualizaDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NumeroLog = new javax.swing.JLabel();
        jTextField_Bairro_ = new javax.swing.JTextField();
        jLabel_Bairro = new javax.swing.JLabel();
        jTextField_UF = new javax.swing.JTextField();
        jLabel_UF = new javax.swing.JLabel();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_Cnpj_ = new javax.swing.JTextField();
        jLabel_CpfCnpj = new javax.swing.JLabel();
        jTextField_Telefone_ = new javax.swing.JTextField();
        jLabel_Telefone = new javax.swing.JLabel();
        jTextField_Email_ = new javax.swing.JTextField();
        jTextField_Cidade_ = new javax.swing.JTextField();
        jLabel_Cidade = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_AvRua_ = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Numero = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jButton_Salvar_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jTextField_Nome_ = new javax.swing.JTextField();
        jLabel_AvRua = new javax.swing.JLabel();
        jTextField_NumeroLog_ = new javax.swing.JTextField();
        jTextField_Ie_ = new javax.swing.JTextField();
        jLabel_Ie = new javax.swing.JLabel();
        jLabel_Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar, Editar ou Deletar");

        jLabel_NumeroLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_NumeroLog.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NumeroLog.setText("Número Log");

        jTextField_Bairro_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Bairro_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Bairro_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Bairro_ActionPerformed(evt);
            }
        });

        jLabel_Bairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Bairro.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Bairro.setText("Bairro");

        jTextField_UF.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_UF.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UFActionPerformed(evt);
            }
        });

        jLabel_UF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_UF.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_UF.setText("UF");

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Nome.setText("Nome");

        jTextField_Cnpj_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Cnpj_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Cnpj_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cnpj_ActionPerformed(evt);
            }
        });

        jLabel_CpfCnpj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_CpfCnpj.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_CpfCnpj.setText("CNPJ");

        jTextField_Telefone_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Telefone_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Telefone_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Telefone_ActionPerformed(evt);
            }
        });

        jLabel_Telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Telefone.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Telefone.setText("Telefone");

        jTextField_Email_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Email_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Email_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email_ActionPerformed(evt);
            }
        });

        jTextField_Cidade_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Cidade_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Cidade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cidade_ActionPerformed(evt);
            }
        });

        jLabel_Cidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Cidade.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cidade.setText("Cidade");

        jLabel_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Email.setText("E-mail");

        jTextField_AvRua_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_AvRua_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_AvRua_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AvRua_ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Empresa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Empresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Empresa.setText("EMPRESA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Empresa)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Empresa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jTextField_Nome_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nome_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nome_ActionPerformed(evt);
            }
        });

        jLabel_AvRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_AvRua.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_AvRua.setText("Av/Rua");

        jTextField_NumeroLog_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_NumeroLog_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_NumeroLog_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumeroLog_ActionPerformed(evt);
            }
        });

        jTextField_Ie_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Ie_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Ie_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Ie_ActionPerformed(evt);
            }
        });

        jLabel_Ie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Ie.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Ie.setText("IE");

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Ie)
                            .addComponent(jTextField_Ie_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Telefone)
                            .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Numero)
                                .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Nome)
                                .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_CpfCnpj)
                                .addComponent(jTextField_Cnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_AvRua))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_NumeroLog)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField_NumeroLog_)
                                    .addGap(43, 43, 43)))
                            .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Bairro)
                                .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Cidade)
                                .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_UF)
                                .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel_Aviso1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_CpfCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Ie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Ie_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_AvRua)
                            .addComponent(jLabel_NumeroLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NumeroLog_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_Salvar_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_UF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Aviso1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Bairro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Bairro_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Bairro_ActionPerformed

    private void jTextField_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UFActionPerformed

    private void jTextField_Cnpj_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cnpj_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cnpj_ActionPerformed

    private void jTextField_Telefone_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Telefone_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Telefone_ActionPerformed

    private void jTextField_Email_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email_ActionPerformed

    private void jTextField_Cidade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cidade_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cidade_ActionPerformed

    private void jTextField_AvRua_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AvRua_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvRua_ActionPerformed

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed

        try
        {
            //  Instanciando objeto da classe cliente
            if(empresa == null)
            empresa = new Empresacliente();

            //  Selecionando os campos a serem salvos
            empresa.setNome(jTextField_Nome_.getText());
            empresa.setTelefone(jTextField_Telefone_.getText());
            empresa.setCnpj(jTextField_Cnpj_.getText());
            empresa.setIe(jTextField_Ie_.getText());
            empresa.setEmail(jTextField_Email_.getText());
            empresa.setAvRua(jTextField_Bairro_.getText());
            empresa.setNumero(jTextField_NumeroLog_.getText());
            empresa.setBairro(jTextField_Bairro_.getText());
            empresa.setCidade(jTextField_Cidade_.getText());
            empresa.setUf(jTextField_UF.getText());

            //  Chamando método para gravar no banco
            DAO.editar(empresa);
            JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");
            
            //  Limpa Campos
            empresa = new Empresacliente();
            atualizaDados();
            
        } catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, s);
            }// Fim do try-catch
       

    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            DAO.remover(empresa);
            
            //  Limpa Campos
            empresa = new Empresacliente();
            atualizaDados();
            
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
        }catch(Exception s)
                {
                    JOptionPane.showMessageDialog(this, "ERRO:" + s);
                }// fim do try-catch
        
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jTextField_Nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_ActionPerformed

    private void jTextField_NumeroLog_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeroLog_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeroLog_ActionPerformed

    private void jTextField_Ie_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Ie_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Ie_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Empresa dialog = new Empresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JLabel jLabel_AvRua;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_Bairro;
    private javax.swing.JLabel jLabel_Cidade;
    private javax.swing.JLabel jLabel_CpfCnpj;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_Ie;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_NumeroLog;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JLabel jLabel_UF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_AvRua_;
    private javax.swing.JTextField jTextField_Bairro_;
    private javax.swing.JTextField jTextField_Cidade_;
    private javax.swing.JTextField jTextField_Cnpj_;
    private javax.swing.JTextField jTextField_Email_;
    private javax.swing.JTextField jTextField_Ie_;
    private javax.swing.JTextField jTextField_Nome_;
    private javax.swing.JTextField jTextField_NumeroLog_;
    private javax.swing.JTextField jTextField_Numero_;
    private javax.swing.JTextField jTextField_Telefone_;
    private javax.swing.JTextField jTextField_UF;
    // End of variables declaration//GEN-END:variables
}
