/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Tipo;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Produto extends javax.swing.JDialog {

    /**
     * Creates new form Produto
     */
    
    models.Produto produto;
    
    public Produto(java.awt.Frame parent, boolean modal, models.Produto produto) {
        super(parent, modal);
        initComponents();
        
        this.produto = produto;
        
        setLocationRelativeTo(null);
        atualizaComboBox(); 
        atualizaDados();
        
    }// Fim do construtor Produto
            
    public Produto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //  Preenchimento dos jComboBox
        atualizaComboBox();
        
    }// Fim do construtor Produto
    
    //  Preenchimento dos jComboBox
    private void atualizaComboBox()
    {
        List tipo = new LinkedList();
        tipo.add("Selecione");
        tipo.addAll(DAO.consulta(Tipo.class, ""));
        jComboBox_Tipo_.setModel(new DefaultComboBoxModel<>(tipo.toArray()));
        
    }// Fim do método atualizaComboBox
    
    private void atualizaDados()
    {
        jTextField_Nome_.setText(produto.getNome());
        jTextArea_DescProduto.setText(produto.getDescricao());
        jTextField_CodBarras_.setText(produto.getCodBarras());
        jComboBox_Tipo_.setSelectedItem(produto.getIdTipo());
        jTextField_Estoque_.setText(produto.getEstoque() + "");
        
    }// Fim do método atualizaDados
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Produto = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jLabel_Numero = new javax.swing.JLabel();
        jTextField_Nome_ = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        jButton_Salvar_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jTextField_Estoque_ = new javax.swing.JTextField();
        jLabel_Estoque = new javax.swing.JLabel();
        jComboBox_Tipo_ = new javax.swing.JComboBox<>();
        jLabel_Tipo = new javax.swing.JLabel();
        jTextField_CodBarras_ = new javax.swing.JTextField();
        jLabel_CodBarras = new javax.swing.JLabel();
        jLabel_DescricaoProd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DescProduto = new javax.swing.JTextArea();
        jLabel_Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar, Editar ou Deletar");

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Produto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Produto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Produto.setText("PRODUTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Produto)
                .addContainerGap(662, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Produto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jTextField_Nome_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nome_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nome_ActionPerformed(evt);
            }
        });

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Nome.setText("Nome");

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jTextField_Estoque_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Estoque_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Estoque_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Estoque_ActionPerformed(evt);
            }
        });

        jLabel_Estoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Estoque.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Estoque.setText("Estoque");

        jComboBox_Tipo_.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Tipo_.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Tipo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Tipo_ActionPerformed(evt);
            }
        });

        jLabel_Tipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Tipo.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Tipo.setText("Tipo");

        jTextField_CodBarras_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_CodBarras_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_CodBarras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CodBarras_ActionPerformed(evt);
            }
        });

        jLabel_CodBarras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_CodBarras.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_CodBarras.setText("Código de Barras");

        jLabel_DescricaoProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DescricaoProd.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DescricaoProd.setText("Descrição do Produto");

        jTextArea_DescProduto.setColumns(20);
        jTextArea_DescProduto.setRows(5);
        jScrollPane1.setViewportView(jTextArea_DescProduto);

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Aviso1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Estoque_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_Estoque))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_Tipo)
                                        .addComponent(jComboBox_Tipo_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_CodBarras)
                                        .addComponent(jTextField_CodBarras_, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel_DescricaoProd)
                                .addComponent(jScrollPane1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_Salvar_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Numero)
                                .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Nome)
                                .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Tipo)
                                .addGap(36, 36, 36))
                            .addComponent(jComboBox_Tipo_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Estoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Estoque_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_CodBarras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_CodBarras_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_DescricaoProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Aviso1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jTextField_Nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_ActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed
            
        try
        {
            //  Instanciando objeto da classe Fornecedor
            if(produto == null)
            produto = new models.Produto();

            //  Selecionando os campos a serem salvos
            produto.setNome(jTextField_Nome_.getText());
            produto.setEstoque(Integer.parseInt(jTextField_Estoque_.getText()));
            produto.setIdTipo((models.Tipo) jComboBox_Tipo_.getSelectedItem());
            produto.setCodBarras(jTextField_CodBarras_.getText());
            produto.setDescricao(jTextArea_DescProduto.getText());

            //  Chamando método para gravar no banco
            DAO.editar(produto);
            JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");
            
            //  Limpa Tela
            produto = new models.Produto();
            atualizaDados();
            atualizaComboBox();
            
        } catch(Exception s)
            {
                JOptionPane.showMessageDialog(this, s);
            }// Fim do try-catch
    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed
        
        try
        {
            DAO.remover(produto);
            
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
            //  Limpa campos
            produto = new models.Produto();
            atualizaDados();
            atualizaComboBox();
            
        }catch(Exception s)
                {
                    JOptionPane.showMessageDialog(this, "ERRO:" + s);
                }// fim do try-catch
        
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jTextField_Estoque_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Estoque_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Estoque_ActionPerformed

    private void jComboBox_Tipo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Tipo_ActionPerformed

    }//GEN-LAST:event_jComboBox_Tipo_ActionPerformed

    private void jTextField_CodBarras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CodBarras_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CodBarras_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Produto dialog = new Produto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private javax.swing.JComboBox<Object> jComboBox_Tipo_;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_CodBarras;
    private javax.swing.JLabel jLabel_DescricaoProd;
    private javax.swing.JLabel jLabel_Estoque;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_Tipo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_DescProduto;
    private javax.swing.JTextField jTextField_CodBarras_;
    private javax.swing.JTextField jTextField_Estoque_;
    private javax.swing.JTextField jTextField_Nome_;
    private javax.swing.JTextField jTextField_Numero_;
    // End of variables declaration//GEN-END:variables
}
