/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas.cadastros;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistence.DAO;

/**
 *
 * @author Altair Mateus T Alencastro
 */
public class Tecnico extends javax.swing.JDialog {

    models.Tecnico tecnico;
            
    public Tecnico(java.awt.Frame parent, boolean modal, models.Tecnico tecnico) {
        super(parent, modal);
        initComponents();
        
        this.tecnico = tecnico;
        
        setLocationRelativeTo(null); 
        atualizaDados();
        
    }// Fim do construtor Tecnico
    
    public Tecnico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }// Fim do construtor Tecnico
    
    private void atualizaDados()
    {
        
        jTextField_Nome_.setText(tecnico.getNome());
        jTextField_Telefone_.setText(tecnico.getTelefone());
        jTextField_CpfCnpj_.setText(tecnico.getCpf());
        jTextField_Email_.setText(tecnico.getEmail());
        jDateChooser_DataNasc.setDate(tecnico.getDataNasc());
        jTextField_AvRua_.setText(tecnico.getAvRua());
        jTextField_NumeroLog_.setText(tecnico.getNumero());
        jTextField_Bairro_.setText(tecnico.getBairro());
        jTextField_Cidade_.setText(tecnico.getCidade());
        jTextField_UF_.setText(tecnico.getUf());
        jPasswordField_Senha.setText(tecnico.getSenha());
        
    }// Fim do método atualizaDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Numero = new javax.swing.JLabel();
        jLabel_Senha = new javax.swing.JLabel();
        jTextField_Numero_ = new javax.swing.JTextField();
        jButton_Salvar_ = new javax.swing.JButton();
        jButton_Deletar = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jTextField_Nome_ = new javax.swing.JTextField();
        jLabel_Nome = new javax.swing.JLabel();
        jTextField_CpfCnpj_ = new javax.swing.JTextField();
        jLabel_CpfCnpj = new javax.swing.JLabel();
        jTextField_Telefone_ = new javax.swing.JTextField();
        jLabel_Telefone = new javax.swing.JLabel();
        jTextField_Email_ = new javax.swing.JTextField();
        jTextField_Cidade_ = new javax.swing.JTextField();
        jLabel_Cidade = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jTextField_AvRua_ = new javax.swing.JTextField();
        jLabel_AvRua = new javax.swing.JLabel();
        jTextField_NumeroLog_ = new javax.swing.JTextField();
        jLabel_NumeroLog = new javax.swing.JLabel();
        jTextField_Bairro_ = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Tecnico = new javax.swing.JLabel();
        jLabel_Bairro = new javax.swing.JLabel();
        jLabel_Cidade1 = new javax.swing.JLabel();
        jDateChooser_DataNasc = new com.toedter.calendar.JDateChooser();
        jTextField_UF_ = new javax.swing.JTextField();
        jLabel_UF = new javax.swing.JLabel();
        jPasswordField_Senha = new javax.swing.JPasswordField();
        jLabel_Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar, Editar ou Deletar");

        jLabel_Numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Numero.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Numero.setText("Número");

        jLabel_Senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Senha.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Senha.setText("Senha");

        jTextField_Numero_.setEditable(false);
        jTextField_Numero_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Numero_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Numero_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Numero_ActionPerformed(evt);
            }
        });

        jButton_Salvar_.setBackground(new java.awt.Color(72, 124, 189));
        jButton_Salvar_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Salvar_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salvar_.setText("SALVAR");
        jButton_Salvar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Salvar_ActionPerformed(evt);
            }
        });

        jButton_Deletar.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Deletar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Deletar.setText("DELETAR");
        jButton_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeletarActionPerformed(evt);
            }
        });

        jButton_Sair_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Sair_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sair_.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Sair_.setText("SAIR");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jTextField_Nome_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nome_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nome_ActionPerformed(evt);
            }
        });

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Nome.setText("Nome");

        jTextField_CpfCnpj_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_CpfCnpj_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_CpfCnpj_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CpfCnpj_ActionPerformed(evt);
            }
        });

        jLabel_CpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_CpfCnpj.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_CpfCnpj.setText("CPF");

        jTextField_Telefone_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Telefone_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Telefone_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Telefone_ActionPerformed(evt);
            }
        });

        jLabel_Telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Telefone.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Telefone.setText("Telefone");

        jTextField_Email_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Email_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Email_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email_ActionPerformed(evt);
            }
        });

        jTextField_Cidade_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Cidade_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Cidade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Cidade_ActionPerformed(evt);
            }
        });

        jLabel_Cidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Cidade.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cidade.setText("Cidade");

        jLabel_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Email.setText("E-mail");

        jTextField_AvRua_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_AvRua_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_AvRua_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AvRua_ActionPerformed(evt);
            }
        });

        jLabel_AvRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_AvRua.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_AvRua.setText("Av/Rua");

        jTextField_NumeroLog_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_NumeroLog_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_NumeroLog_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumeroLog_ActionPerformed(evt);
            }
        });

        jLabel_NumeroLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_NumeroLog.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NumeroLog.setText("Número Log");

        jTextField_Bairro_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Bairro_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Bairro_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Bairro_ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(72, 124, 189));

        jLabel_Tecnico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Tecnico.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tecnico.setText("TÉCNICO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Tecnico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Tecnico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Bairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Bairro.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Bairro.setText("Bairro");

        jLabel_Cidade1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Cidade1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Cidade1.setText("Data Nasc");

        jDateChooser_DataNasc.setDateFormatString("dd/MM/yyyy");
        jDateChooser_DataNasc.setMinSelectableDate(new java.util.Date(-62135755101000L));

        jTextField_UF_.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_UF_.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_UF_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UF_ActionPerformed(evt);
            }
        });

        jLabel_UF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_UF.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_UF.setText("UF");

        jLabel_Aviso1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Aviso1.setForeground(new java.awt.Color(73, 124, 190));
        jLabel_Aviso1.setText("CAMPOS EM AZUL SÃO OBRIGATÓRIOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Numero)
                            .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nome)
                            .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CpfCnpj)
                            .addComponent(jTextField_CpfCnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_AvRua))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_NumeroLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_NumeroLog_)
                                .addGap(43, 43, 43)))
                        .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Bairro)
                            .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cidade)
                            .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_UF_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_UF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Senha)
                            .addComponent(jPasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Telefone)
                            .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_Email_, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cidade1)
                            .addComponent(jDateChooser_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_Aviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Numero_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_CpfCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CpfCnpj_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Telefone_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Cidade1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Email_, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDateChooser_DataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Salvar_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_AvRua)
                            .addComponent(jLabel_NumeroLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_AvRua_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NumeroLog_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Cidade_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Bairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Bairro_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_UF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_UF_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel_Senha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Aviso1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Numero_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Numero_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Numero_ActionPerformed

    private void jButton_Salvar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Salvar_ActionPerformed

    try
    {
        //  Instanciando objeto da classe tecnico
        if(tecnico == null)
        tecnico = new models.Tecnico();

        //  Selecionando os campos a serem salvos
        tecnico.setNome(jTextField_Nome_.getText());
        tecnico.setCpf(jTextField_CpfCnpj_.getText());
        tecnico.setTelefone(jTextField_Telefone_.getText());
        tecnico.setEmail(jTextField_Email_.getText());
        tecnico.setDataNasc(jDateChooser_DataNasc.getDate());
        tecnico.setAvRua(jTextField_Bairro_.getText());
        tecnico.setNumero(jTextField_NumeroLog_.getText());
        tecnico.setBairro(jTextField_Bairro_.getText());
        tecnico.setCidade(jTextField_Cidade_.getText());
        tecnico.setUf(jTextField_UF_.getText());
        tecnico.setSenha(jPasswordField_Senha.getText());

        //  Chamando método para gravar no banco
        DAO.editar(tecnico);
        JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO");
        
        //  Limpa campos
        tecnico = new models.Tecnico();
        atualizaDados();
            
    } catch(Exception s)
        {
            JOptionPane.showMessageDialog(this, s);
        }// Fim do try-catch
        
        

    }//GEN-LAST:event_jButton_Salvar_ActionPerformed

    private void jButton_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeletarActionPerformed

        try
        {
            DAO.remover(tecnico);
            
            JOptionPane.showMessageDialog(this, "EXCLUÍDO COM SUCESSO");
            
            //  Limpa campos
            tecnico = new models.Tecnico();
            atualizaDados();
            
        }catch(Exception s)
                {
                    JOptionPane.showMessageDialog(this, "ERRO:" + s);
                }// fim do try-catch
        
    }//GEN-LAST:event_jButton_DeletarActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed

        //  Retorna a tela principal
        this.dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jTextField_Nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_ActionPerformed

    private void jTextField_CpfCnpj_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CpfCnpj_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CpfCnpj_ActionPerformed

    private void jTextField_Telefone_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Telefone_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Telefone_ActionPerformed

    private void jTextField_Email_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email_ActionPerformed

    private void jTextField_Cidade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Cidade_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Cidade_ActionPerformed

    private void jTextField_AvRua_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AvRua_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AvRua_ActionPerformed

    private void jTextField_NumeroLog_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumeroLog_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumeroLog_ActionPerformed

    private void jTextField_Bairro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Bairro_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Bairro_ActionPerformed

    private void jTextField_UF_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UF_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UF_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tecnico dialog = new Tecnico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deletar;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JButton jButton_Salvar_;
    private com.toedter.calendar.JDateChooser jDateChooser_DataNasc;
    private javax.swing.JLabel jLabel_AvRua;
    private javax.swing.JLabel jLabel_Aviso1;
    private javax.swing.JLabel jLabel_Bairro;
    private javax.swing.JLabel jLabel_Cidade;
    private javax.swing.JLabel jLabel_Cidade1;
    private javax.swing.JLabel jLabel_CpfCnpj;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Numero;
    private javax.swing.JLabel jLabel_NumeroLog;
    private javax.swing.JLabel jLabel_Senha;
    private javax.swing.JLabel jLabel_Tecnico;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JLabel jLabel_UF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_Senha;
    private javax.swing.JTextField jTextField_AvRua_;
    private javax.swing.JTextField jTextField_Bairro_;
    private javax.swing.JTextField jTextField_Cidade_;
    private javax.swing.JTextField jTextField_CpfCnpj_;
    private javax.swing.JTextField jTextField_Email_;
    private javax.swing.JTextField jTextField_Nome_;
    private javax.swing.JTextField jTextField_NumeroLog_;
    private javax.swing.JTextField jTextField_Numero_;
    private javax.swing.JTextField jTextField_Telefone_;
    private javax.swing.JTextField jTextField_UF_;
    // End of variables declaration//GEN-END:variables
}
